
CREATE TABLE global_finance_ExchangeRate (
  ExchangeRateType NVARCHAR(4) NOT NULL,
  SourceCurrency NVARCHAR(5) NOT NULL,
  TargetCurrency NVARCHAR(5) NOT NULL,
  ExchangeRateEffectiveDate DATE NOT NULL,
  ExchangeRate DECIMAL(9, 5),
  PRIMARY KEY(ExchangeRateType, SourceCurrency, TargetCurrency, ExchangeRateEffectiveDate)
);

CREATE TABLE JournalEntry_PreAsientoContable (
  PreAsientoContableId NVARCHAR(36) NOT NULL,
  DocumentoCodigo NVARCHAR(15),
  NumeroDocumentoOrigen NVARCHAR(30),
  AccountingDocumentType NVARCHAR(5),
  CompanyCode NVARCHAR(4),
  DocumentDate SECONDDATE,
  PostingDate SECONDDATE,
  TransactionCurrency NVARCHAR(3),
  CompanyCodeCurrency NVARCHAR(3),
  GroupCurrency NVARCHAR(3),
  FreeDefinedCurrency NVARCHAR(3),
  CreatedByUser NVARCHAR(13),
  OriginalReferenceDocument NVARCHAR(20),
  OriginalReferenceDocumentLogicalSystem NVARCHAR(10),
  AccountingDocument NVARCHAR(10),
  DocumentReferenceID NVARCHAR(16),
  DocumentHeaderText NVARCHAR(25),
  ReversalReason NVARCHAR(2),
  ReversalReferenceDocument NVARCHAR(20),
  ReversalDate SECONDDATE,
  TaxReportingDate SECONDDATE,
  TaxDeterminationDate SECONDDATE,
  TaxFulfillmentDate SECONDDATE,
  DoTaxAmountCheck NVARCHAR(1),
  InvoiceReceiptDate SECONDDATE,
  ExchangeRateDate SECONDDATE,
  IndirectQuotedExchangeRate DECIMAL(28, 6),
  ExchangeRate DECIMAL(28, 6),
  SourceSystemCompanyCode NVARCHAR(20),
  SourceSystemAccountingDocument NVARCHAR(35),
  Reference1InDocumentHeader NVARCHAR(20),
  Reference2InDocumentHeader NVARCHAR(20),
  JrnlEntryCntrySpecificRef1 NVARCHAR(80),
  JrnlEntryCntrySpecificDate1 SECONDDATE,
  JrnlEntryCntrySpecificRef2 NVARCHAR(25),
  JrnlEntryCntrySpecificDate2 SECONDDATE,
  JrnlEntryCntrySpecificRef3 NVARCHAR(25),
  JrnlEntryCntrySpecificDate3 SECONDDATE,
  JrnlEntryCntrySpecificRef4 NVARCHAR(50),
  JrnlEntryCntrySpecificDate4 SECONDDATE,
  JrnlEntryCntrySpecificRef5 NVARCHAR(50),
  JrnlEntryCntrySpecificDate5 SECONDDATE,
  JrnlEntryCntrySpecificBp1 NVARCHAR(10),
  JrnlEntryCntrySpecificBp2 NVARCHAR(10),
  NroDocumentoSap NVARCHAR(30),
  FechaHoraCreacion TIMESTAMP,
  Flujo NVARCHAR(1),
  to_Status_statusId INTEGER,
  PRIMARY KEY(PreAsientoContableId)
);

CREATE TABLE JournalEntry_PreAsientoContableGLAccountItem (
  PreAsientoContableGLAccountItemId NVARCHAR(36) NOT NULL,
  DocumentoCodigo NVARCHAR(15),
  NumeroDocumentoOrigen NVARCHAR(30),
  GlAccount NVARCHAR(10),
  AmountInTransactionCurrency DECIMAL(28, 6),
  ItemGroup NVARCHAR(6),
  CompanyCode NVARCHAR(4),
  AmountInCompanyCodeCurrency DECIMAL(28, 6),
  AmountInGroupCurrency DECIMAL(28, 6),
  AmountInFreeDefinedCurrency DECIMAL(28, 6),
  DebitCreditCode NVARCHAR(1),
  DocumentItemText NVARCHAR(50),
  BusinessPlace NVARCHAR(3),
  ReasonCode NVARCHAR(3),
  AssignmentReference NVARCHAR(18),
  OplAcctgDocItmCntrySpcfcRef NVARCHAR(50),
  FinancialTransactionType NVARCHAR(3),
  Plant NVARCHAR(4),
  Material NVARCHAR(60),
  QuantityInEntryUnit DECIMAL(31, 14),
  UnitCode NVARCHAR(3),
  IsNotCashDiscountLiable NVARCHAR(1),
  TradingPartner NVARCHAR(6),
  ValueDate SECONDDATE,
  HouseBank NVARCHAR(5),
  HouseBankAccount NVARCHAR(5),
  Reference1IDByBusinessPartner NVARCHAR(12),
  Reference2IDByBusinessPartner NVARCHAR(12),
  Reference3IDByBusinessPartner NVARCHAR(20),
  TaxCode NVARCHAR(4),
  TaxJurisdiction NVARCHAR(15),
  TaxItemGroup NVARCHAR(6),
  TaxCountry NVARCHAR(3),
  TaxExpenseAmountInTransCrcy DECIMAL(28, 6),
  TaxExpenseAmountInCoCodeCrcy DECIMAL(28, 6),
  TaxExpenseAmountInGroupCrcy DECIMAL(28, 6),
  TaxExpenseAmountInFreeDefinedCrcy DECIMAL(28, 6),
  AccountAssignmentType NVARCHAR(2),
  AccAsgnProfitCenter NVARCHAR(10),
  AccAsgnPartnerProfitCenter NVARCHAR(10),
  AccAsgnSegment NVARCHAR(10),
  AccAsgnPartnerSegment NVARCHAR(10),
  AccAsgnCostCenter NVARCHAR(10),
  AccAsgnCostCtrActivityType NVARCHAR(6),
  AccAsgnWBSElement NVARCHAR(24),
  AccAsgnMasterFixedAsset NVARCHAR(12),
  AccAsgnFixedAsset NVARCHAR(4),
  AccAsgnSalesOrder NVARCHAR(10),
  AccAsgnSalesOrderItem NVARCHAR(6),
  AccAsgnFunctionalArea NVARCHAR(16),
  AccAsgnServiceDocType NVARCHAR(4),
  AccAsgnServiceDocID NVARCHAR(10),
  AccAsgnServiceDocItemID NVARCHAR(6),
  AccAsgnWorkItem NVARCHAR(10),
  ProfSuplCustomer NVARCHAR(10),
  ProfSuplCustomerGroup NVARCHAR(2),
  ProfSuplCustomerIndustry NVARCHAR(10),
  ProfSuplCustomerCountry NVARCHAR(3),
  ProfSuplSalesDistrict NVARCHAR(6),
  ProfSuplSoldMaterial NVARCHAR(18),
  ProfSuplSoldMaterialGroup NVARCHAR(9),
  ProfSuplSalesOrganization NVARCHAR(4),
  ProfSuplDistributionChannel NVARCHAR(2),
  ProfSuplDivision NVARCHAR(2),
  ProfSuplBillToParty NVARCHAR(10),
  ProfSuplShipToParty NVARCHAR(10),
  ProfSuplPersonnelNumber NVARCHAR(8),
  ProfSuplWBSElement NVARCHAR(24),
  ProfSuplFunctionalArea NVARCHAR(16),
  ProfSuplServiceDocType NVARCHAR(4),
  ProfSuplServiceDocID NVARCHAR(10),
  ProfSuplServiceDocItemID NVARCHAR(6),
  AddAtrPersonnelNumber NVARCHAR(6),
  to_PreAsientoContable_PreAsientoContableId NVARCHAR(36),
  PRIMARY KEY(PreAsientoContableGLAccountItemId)
);

CREATE TABLE JournalEntry_PreAsientoContableCustomerAccountItem (
  PreAsientoContableCustomerAccountItemId NVARCHAR(36) NOT NULL,
  DocumentoCodigo NVARCHAR(15),
  NumeroDocumentoOrigen NVARCHAR(30),
  Debtor NVARCHAR(10),
  AmountInTransactionCurrency DECIMAL(28, 6),
  AmountInCompanyCodeCurrency DECIMAL(28, 6),
  AmountInGroupCurrency DECIMAL(28, 6),
  AmountInFreeDefinedCurrency DECIMAL(28, 6),
  DebitCreditCode NVARCHAR(1),
  AltvRecnclnAccts NVARCHAR(10),
  ReportingCountry NVARCHAR(3),
  DocumentItemText NVARCHAR(50),
  AssignmentReference NVARCHAR(18),
  OplAcctgDocItmCntrySpcfcRef NVARCHAR(50),
  Reference1IDByBusinessPartner NVARCHAR(12),
  Reference2IDByBusinessPartner NVARCHAR(12),
  Reference3IDByBusinessPartner NVARCHAR(20),
  CreditControlArea NVARCHAR(4),
  StateCentralBankPaymentReason NVARCHAR(3),
  VatRegistration NVARCHAR(20),
  BranchAccount NVARCHAR(10),
  BusinessPlace NVARCHAR(4),
  TaxCountry NVARCHAR(3),
  HouseBank NVARCHAR(5),
  HouseBankAccount NVARCHAR(5),
  JointVentureBillingType NVARCHAR(2),
  DueCalculationBaseDate SECONDDATE,
  CashDiscountBaseAmount DECIMAL(28, 6),
  CashDiscount1Days INTEGER,
  CashDiscount1Percent DECIMAL(16, 6),
  CashDiscount2Days INTEGER,
  CashDiscount2Percent DECIMAL(16, 6),
  NetPaymentDays NVARCHAR(10),
  PaymentMethod NVARCHAR(1),
  PaymentReason NVARCHAR(4),
  PaymentBlockingReason NVARCHAR(2),
  PaymentServiceProvider NVARCHAR(4),
  PaymentByPaymentServicePrvdr NVARCHAR(35),
  SpecialGLCode NVARCHAR(1),
  TaxCode NVARCHAR(4),
  TaxJurisdiction NVARCHAR(15),
  TaxItemGroup NVARCHAR(6),
  OneTimeCustName NVARCHAR(35),
  OneTimeCustCityName NVARCHAR(35),
  OneTimeCustCountry NVARCHAR(3),
  OneTimeCustBankCountry NVARCHAR(3),
  OneTimeCustBankAccount NVARCHAR(18),
  OneTimeCustBankControlKey NVARCHAR(2),
  OneTimeCustBankNumber NVARCHAR(15),
  OneTimeCustTaxNumber1 NVARCHAR(16),
  OneTimeCustTaxNumber2 NVARCHAR(11),
  OneTimeCustTaxNumber3 NVARCHAR(18),
  OneTimeCustTaxNumber4 NVARCHAR(18),
  OneTimeCustTaxNumber5 NVARCHAR(60),
  OneTimeCustIsNaturalPerson NVARCHAR(1),
  OneTimeCustRegion NVARCHAR(3),
  OneTimeCustVATLiability NVARCHAR(1),
  OneTimeCustTaxNumberType NVARCHAR(2),
  to_PreAsientoContable_PreAsientoContableId NVARCHAR(36),
  PRIMARY KEY(PreAsientoContableCustomerAccountItemId)
);

CREATE TABLE JournalEntry_PreAsientoContableSupplierAccountItem (
  PreAsientoContableSupplierAccountItemId NVARCHAR(36) NOT NULL,
  DocumentoCodigo NVARCHAR(15),
  NumeroDocumentoOrigen NVARCHAR(30),
  Creditor NVARCHAR(10),
  AmountInTransactionCurrency DECIMAL(28, 6),
  AmountInCompanyCodeCurrency DECIMAL(28, 6),
  AmountInGroupCurrency DECIMAL(28, 6),
  AmountInFreeDefinedCurrency DECIMAL(28, 6),
  DebitCreditCode NVARCHAR(1),
  AltvRecnclnAccts NVARCHAR(10),
  DocumentItemText NVARCHAR(50),
  AssignmentReference NVARCHAR(18),
  OplAcctgDocItmCntrySpcfcRef NVARCHAR(50),
  Reference1IDByBusinessPartner NVARCHAR(12),
  Reference2IDByBusinessPartner NVARCHAR(12),
  Reference3IDByBusinessPartner NVARCHAR(20),
  StateCentralBankPaymentReason NVARCHAR(3),
  BranchAccount NVARCHAR(10),
  BusinessPlace NVARCHAR(4),
  TaxCountry NVARCHAR(3),
  HouseBank NVARCHAR(5),
  HouseBankAccount NVARCHAR(5),
  DueCalculationBaseDate SECONDDATE,
  CashDiscountBaseAmount DECIMAL(28, 6),
  CashDiscount1Days INTEGER,
  CashDiscount1Percent DECIMAL(16, 6),
  CashDiscount2Days INTEGER,
  CashDiscount2Percent DECIMAL(16, 6),
  NetPaymentDays NVARCHAR(10),
  PaymentMethod NVARCHAR(1),
  PaymentReason NVARCHAR(4),
  PaymentBlockingReason NVARCHAR(2),
  AlternativePayee NVARCHAR(10),
  PayeeCountry NVARCHAR(3),
  PayeeBankNumber NVARCHAR(15),
  PayeeSWIFTCode NVARCHAR(11),
  PayeeBankAccount NVARCHAR(18),
  PayeeIBAN NVARCHAR(34),
  PayeeBankAccountHolderName NVARCHAR(60),
  SpecialGLCode NVARCHAR(1),
  TaxCode NVARCHAR(4),
  TaxJurisdiction NVARCHAR(15),
  TaxItemGroup NVARCHAR(6),
  OneTimeVendorName NVARCHAR(35),
  OneTimeVendorCityName NVARCHAR(35),
  OneTimeVendorCountry NVARCHAR(3),
  to_PreAsientoContable_PreAsientoContableId NVARCHAR(36),
  PRIMARY KEY(PreAsientoContableSupplierAccountItemId)
);

CREATE TABLE JournalEntry_PreAsientoContableTaxAccountItem (
  PreAsientoContableTaxAccountItemId NVARCHAR(36) NOT NULL,
  DocumentoCodigo NVARCHAR(15),
  NumeroDocumentoOrigen NVARCHAR(30),
  TaxCode NVARCHAR(10),
  AmountInTransactionCurrency DECIMAL(28, 6),
  TaxItemClassification NVARCHAR(3),
  ConditionType NVARCHAR(4),
  TaxJurisdiction NVARCHAR(15),
  TaxJurisdictionLevel NVARCHAR(1),
  LowestLevelTaxJurisdiction NVARCHAR(15),
  TaxItemGroup NVARCHAR(6),
  TaxCountry NVARCHAR(3),
  TaxRate DECIMAL(16, 6),
  TaxDeterminationDate SECONDDATE,
  IsDirectTaxPosting NVARCHAR(1),
  AmountInCompanyCodeCurrency DECIMAL(28, 6),
  AmountInGroupCurrency DECIMAL(28, 6),
  AmountInFreeDefinedCurrency DECIMAL(28, 6),
  DebitCreditCode NVARCHAR(1),
  ProductiveTaxText NVARCHAR(50),
  TaxBaseAmountInTransCrcy DECIMAL(28, 6),
  TaxBaseAmountInCoCodeCrcy DECIMAL(28, 6),
  TaxBaseAmountInGroupCrcy DECIMAL(28, 6),
  TaxBaseAmountInFreeDefinedCrcy DECIMAL(28, 6),
  to_PreAsientoContable_PreAsientoContableId NVARCHAR(36),
  PRIMARY KEY(PreAsientoContableTaxAccountItemId)
);

CREATE TABLE JournalEntry_PreAsientoContableWithholdingTaxAccountItem (
  PreAsientoContableWithholdingTaxAccountItemId NVARCHAR(36) NOT NULL,
  DocumentoCodigo NVARCHAR(15),
  NumeroDocumentoOrigen NVARCHAR(30),
  WithholdingTaxType NVARCHAR(2),
  WithholdingTaxCode NVARCHAR(2),
  TaxBaseAmountInTransCrcy DECIMAL(28, 6),
  AmountInTransactionCurrency DECIMAL(28, 6),
  AmountInCompanyCodeCurrency DECIMAL(28, 6),
  AmountInGroupCurrency DECIMAL(28, 6),
  AmountInFreeDefinedCurrency DECIMAL(28, 6),
  TaxBaseAmountInCoCodeCrcy DECIMAL(28, 6),
  TaxBaseAmountInGroupCrcy DECIMAL(28, 6),
  TaxBaseAmountInFreeDefinedCrcy DECIMAL(28, 6),
  TaxIsToBeCalculated NVARCHAR(1),
  to_PreAsientoContable_PreAsientoContableId NVARCHAR(36),
  PRIMARY KEY(PreAsientoContableWithholdingTaxAccountItemId)
);

CREATE TABLE JournalEntry_PreAsientoContableLog (
  PreAsientoContableLogId NVARCHAR(36) NOT NULL,
  NroDocumentoOrigen NVARCHAR(30),
  DocumentoCodigo NVARCHAR(15),
  Accion NVARCHAR(20),
  Mensaje NVARCHAR(300),
  Comentario NVARCHAR(100),
  Usuario NVARCHAR(100),
  FechaHora TIMESTAMP,
  to_PreAsientoContable_PreAsientoContableId NVARCHAR(36),
  PRIMARY KEY(PreAsientoContableLogId)
);

CREATE TABLE master_data_MasterDataStatus (
  statusId INTEGER NOT NULL,
  statusDescription NVARCHAR(50),
  PRIMARY KEY(statusId)
);

CREATE TABLE Letras_Planilla (
  ID NVARCHAR(36) NOT NULL,
  createdAt TIMESTAMP,
  createdBy NVARCHAR(255),
  modifiedAt TIMESTAMP,
  modifiedBy NVARCHAR(255),
  NroLetras INTEGER,
  Planilla NVARCHAR(20),
  ImporteTotal DECIMAL(18, 2),
  ImporteDolares DECIMAL(18, 2),
  Moneda NVARCHAR(3),
  Customer NVARCHAR(20),
  Banco_ID NVARCHAR(36),
  ExchangeRate DECIMAL(10, 2),
  ExchangeRateDate DATE,
  Sequence INTEGER,
  Sociedad_companyCode NVARCHAR(4),
  EstadoPlanilla_Codigo NVARCHAR(10),
  PRIMARY KEY(ID)
);

CREATE TABLE Letras_Banco (
  ID NVARCHAR(36) NOT NULL,
  createdAt TIMESTAMP,
  createdBy NVARCHAR(255),
  modifiedAt TIMESTAMP,
  modifiedBy NVARCHAR(255),
  Codigo NVARCHAR(20),
  Nombre NVARCHAR(100),
  PRIMARY KEY(ID)
);

CREATE TABLE master_data_Company (
  companyCode NVARCHAR(4) NOT NULL,
  companyCodeName NVARCHAR(25),
  cityName NVARCHAR(25),
  country NVARCHAR(3),
  currency NVARCHAR(5),
  "LANGUAGE" NVARCHAR(2),
  company NVARCHAR(6),
  creditControlArea NVARCHAR(4),
  extendedWhldgTaxIsActive BOOLEAN,
  companyLogo NVARCHAR(5000),
  companyIdentification NVARCHAR(20),
  companyPrincipalAddress NVARCHAR(300),
  PRIMARY KEY(companyCode)
);

CREATE TABLE Letras_EstadoPlanilla (
  Codigo NVARCHAR(10) NOT NULL,
  Descripcion NVARCHAR(50),
  PRIMARY KEY(Codigo)
);

CREATE TABLE Letras_Letras (
  ID NVARCHAR(36) NOT NULL,
  createdAt TIMESTAMP,
  createdBy NVARCHAR(255),
  modifiedAt TIMESTAMP,
  modifiedBy NVARCHAR(255),
  Code NVARCHAR(20),
  Sequence INTEGER,
  Documento NVARCHAR(200),
  Serie NVARCHAR(10),
  Numero NVARCHAR(20),
  CodigoMoneda NVARCHAR(3),
  FechaEmision DATE,
  Dias INTEGER,
  FechaVencimiento DATE,
  TipoCambio DECIMAL(10, 2),
  Referencia NVARCHAR(200),
  TotalMonedaDocumento DECIMAL(13, 2),
  TotalDolares DECIMAL(13, 2),
  Vendedor NVARCHAR(100),
  CodigoJournalEntry NVARCHAR(10),
  JournalEntryItem NVARCHAR(6),
  FiscalYear NVARCHAR(4),
  EstadoLetras_Codigo NVARCHAR(10),
  Planilla_ID NVARCHAR(36),
  TipoLetra_Codigo NVARCHAR(10),
  PRIMARY KEY(ID)
);

CREATE TABLE Letras_EstadoLetras (
  Codigo NVARCHAR(10) NOT NULL,
  Descripcion NVARCHAR(50),
  PRIMARY KEY(Codigo)
);

CREATE TABLE Letras_TipoLetra (
  Codigo NVARCHAR(10) NOT NULL,
  Descripcion NVARCHAR(50),
  GlAccount NVARCHAR(10),
  PRIMARY KEY(Codigo)
);

CREATE TABLE Letras_CuentaPorCobrar (
  ID NVARCHAR(36) NOT NULL,
  createdAt TIMESTAMP,
  createdBy NVARCHAR(255),
  modifiedAt TIMESTAMP,
  modifiedBy NVARCHAR(255),
  Planilla_ID NVARCHAR(36),
  SourceLedger NVARCHAR(2),
  CompanyCode NVARCHAR(4),
  FiscalYear NVARCHAR(4),
  AccountingDocument NVARCHAR(10),
  LedgerGLLineItem NVARCHAR(6),
  Ledger NVARCHAR(2),
  CompanyCodeName NVARCHAR(25),
  AccountingDocumentType NVARCHAR(2),
  NetDueDate DATE,
  Customer NVARCHAR(10),
  CustomerTaxNumber1 NVARCHAR(16),
  CustomerHouseBank NVARCHAR(5),
  TaxNumberType NVARCHAR(2),
  CustomerFullName NVARCHAR(220),
  ClearingDate DATE,
  ClearingAccountingDocumentType NVARCHAR(2),
  ClearingJournalEntry NVARCHAR(10),
  DocumentReferenceID NVARCHAR(16),
  ReferenceDocument NVARCHAR(10),
  DocumentDate DATE,
  TransactionCurrency NVARCHAR(5),
  HouseBank NVARCHAR(5),
  HouseBankAccount NVARCHAR(5),
  BalanceTransactionCurrency NVARCHAR(5),
  AmountInBalanceTransacCrcy DECIMAL(18, 2),
  GLAccount NVARCHAR(10),
  IsReversal BOOLEAN,
  IsReversed BOOLEAN,
  DocumentItemText NVARCHAR(50),
  FinancialAccountType NVARCHAR(1),
  ReversalReferenceDocumentCntxt NVARCHAR(10),
  ReversalReferenceDocument NVARCHAR(10),
  EstadoCobranzaValue NVARCHAR(50),
  EstadoCobranzaDescription NVARCHAR(100),
  BillToParty NVARCHAR(10),
  EstadoFacturacionValue NVARCHAR(50),
  EstadoFacturacionDescription NVARCHAR(100),
  AmountInCompanyCodeCurrency DECIMAL(18, 2),
  AmountInGlobalCurrency DECIMAL(18, 2),
  AmountInTransactionCurrency DECIMAL(18, 2),
  CompanyCodeCurrency NVARCHAR(5),
  GlobalCurrency NVARCHAR(5),
  BusinessPartnerIDByExtSystem NVARCHAR(20),
  PostingDate DATE,
  IndEliminado BOOLEAN DEFAULT FALSE,
  IndRefinanciado BOOLEAN DEFAULT FALSE,
  PRIMARY KEY(ID)
);

CREATE TABLE Letras_PlanillaLog (
  ID NVARCHAR(36) NOT NULL,
  createdAt TIMESTAMP,
  createdBy NVARCHAR(255),
  modifiedAt TIMESTAMP,
  modifiedBy NVARCHAR(255),
  Evento NVARCHAR(100) NOT NULL,
  Detalle NCLOB,
  Planilla_ID NVARCHAR(36) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE Letras_LetrasLog (
  ID NVARCHAR(36) NOT NULL,
  createdAt TIMESTAMP,
  createdBy NVARCHAR(255),
  modifiedAt TIMESTAMP,
  modifiedBy NVARCHAR(255),
  Evento NVARCHAR(100) NOT NULL,
  Detalle NCLOB,
  Letras_ID NVARCHAR(36) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE master_data_Currency (
  CurrencyCode NVARCHAR(3) NOT NULL,
  CurrencyName NVARCHAR(25),
  CurrencySymbol NVARCHAR(5),
  PRIMARY KEY(CurrencyCode)
);

CREATE TABLE master_data_GlobalSetting (
  createdAt TIMESTAMP,
  createdBy NVARCHAR(255),
  modifiedAt TIMESTAMP,
  modifiedBy NVARCHAR(255),
  GlobalSettingId INTEGER NOT NULL,
  GlobalSettingModule NVARCHAR(100) NOT NULL,
  GlobalSettingType NVARCHAR(100) NOT NULL,
  GlobalSettingName NVARCHAR(100) NOT NULL,
  GlobalSettingClassification NVARCHAR(20),
  GlobalSettingCode NVARCHAR(20),
  GlobalSettingValue NVARCHAR(500),
  GlobalSettingValue2 NVARCHAR(100),
  GlobalSettingValue3 NVARCHAR(100),
  GlobalSettingValue4 NVARCHAR(100),
  GlobalSettingValue5 NVARCHAR(100),
  GlobalSettingDescription NVARCHAR(200),
  GlobalSettingPatternId INTEGER,
  GlobalSettingStatus NVARCHAR(20),
  GlobalSettingIsEditable BOOLEAN,
  GlobalSettingIsDeletable BOOLEAN,
  GlobalSettingIsBlocked BOOLEAN,
  terminal NVARCHAR(100),
  PRIMARY KEY(GlobalSettingId)
);

CREATE TABLE queue_Queue (
  createdAt TIMESTAMP,
  createdBy NVARCHAR(255),
  modifiedAt TIMESTAMP,
  modifiedBy NVARCHAR(255),
  ID NVARCHAR(36) NOT NULL,
  EventType NVARCHAR(50),
  Status NVARCHAR(20),
  ProcessedAt TIMESTAMP,
  Priority INTEGER,
  RetryCount INTEGER DEFAULT 0,
  RetryMax INTEGER DEFAULT 0,
  Payload NCLOB,
  PayloadHash NVARCHAR(100),
  ErrorMessage NCLOB,
  CorrelationId NVARCHAR(50),
  ObjectId NVARCHAR(100),
  PRIMARY KEY(ID)
);

CREATE TABLE trazabilidad_EventType (
  Code NVARCHAR(50) NOT NULL,
  Name NVARCHAR(50),
  Description NVARCHAR(200),
  Enable BOOLEAN,
  to_OriginSystem_Code NVARCHAR(20),
  to_TargetSystem_Code NVARCHAR(20),
  PRIMARY KEY(Code)
);

CREATE TABLE trazabilidad_System (
  Code NVARCHAR(20) NOT NULL,
  Name NVARCHAR(50),
  PRIMARY KEY(Code)
);

CREATE TABLE trazabilidad_Status (
  Code NVARCHAR(20) NOT NULL,
  Name NVARCHAR(50),
  Color INTEGER,
  Description NVARCHAR(200),
  PRIMARY KEY(Code)
);

CREATE TABLE trazabilidad_RequestType (
  Code NVARCHAR(10) NOT NULL,
  Name NVARCHAR(50),
  PRIMARY KEY(Code)
);

CREATE TABLE trazabilidad_MethodType (
  Code NVARCHAR(10) NOT NULL,
  Name NVARCHAR(50),
  PRIMARY KEY(Code)
);

CREATE TABLE trazabilidad_Event (
  ID NVARCHAR(36) NOT NULL,
  EventInitDateTime TIMESTAMP,
  EventFinishDateTime TIMESTAMP,
  to_EventType_Code NVARCHAR(50),
  to_Status_Code NVARCHAR(20),
  PRIMARY KEY(ID)
);

CREATE TABLE trazabilidad_EventDetail (
  ID NVARCHAR(36) NOT NULL,
  Url NVARCHAR(5000),
  StartDateTime TIMESTAMP,
  EndDateTime TIMESTAMP,
  RequestContent NCLOB,
  ResponseContent NCLOB,
  ErrorMessage NCLOB,
  AttemptNumber INTEGER,
  to_Event_ID NVARCHAR(36),
  to_OriginSystem_Code NVARCHAR(20),
  to_TargetSystem_Code NVARCHAR(20),
  to_Status_Code NVARCHAR(20),
  to_Action_Code NVARCHAR(50),
  to_Method_Code NVARCHAR(10),
  to_RequestType_Code NVARCHAR(10),
  PRIMARY KEY(ID)
);

CREATE TABLE wms_ItemAndBarcode (
  createdAt TIMESTAMP,
  createdBy NVARCHAR(255),
  modifiedAt TIMESTAMP,
  modifiedBy NVARCHAR(255),
  "PRODUCT" NVARCHAR(50) NOT NULL,
  PartA NVARCHAR(30),
  DescriptionItem NVARCHAR(255),
  Barcode NVARCHAR(40),
  UnitCost NVARCHAR(10),
  UnitLenght DECIMAL(13, 3),
  UnitWidth DECIMAL(13, 3),
  UnitHeight DECIMAL(13, 3),
  UnitWeight DECIMAL(13, 3),
  UnitVolume DECIMAL(13, 3),
  SeasonCode NVARCHAR(30),
  BrandCode NVARCHAR(30),
  CustAttr1 NVARCHAR(30),
  RetailPrice NVARCHAR(10),
  NetCost NVARCHAR(10),
  CurrencyCode NVARCHAR(10),
  BarcodePack NVARCHAR(40),
  StdPackQty DECIMAL(5, 0),
  StdPackLength DECIMAL(13, 3),
  StdPackWidth DECIMAL(13, 3),
  StdPackHeight DECIMAL(13, 3),
  StdPackWeight DECIMAL(13, 3),
  StdPackVolume DECIMAL(13, 3),
  BarcodeCase NVARCHAR(40),
  StdCaseQty DECIMAL(5, 0),
  MaxCaseQty DECIMAL(5, 0),
  StdCaseLength DECIMAL(13, 3),
  StdCaseWidth DECIMAL(13, 3),
  StdCaseHeight DECIMAL(13, 3),
  StdCaseWeight DECIMAL(13, 3),
  StdCaseVolume DECIMAL(13, 3),
  Dimension1 NVARCHAR(20),
  Dimension2 NVARCHAR(20),
  Dimension3 NVARCHAR(20),
  Hierarchy1Code NVARCHAR(20),
  Hierarchy1Description NVARCHAR(50),
  Hierarchy2Code NVARCHAR(20),
  Hierarchy3Code NVARCHAR(20),
  Hierarchy3Description NVARCHAR(50),
  Hierarchy4Code NVARCHAR(20),
  GroupCode NVARCHAR(20),
  GroupDescription NVARCHAR(50),
  ExternalStyle NVARCHAR(50),
  VasGroupCode NVARCHAR(30),
  ShortDescr NVARCHAR(30),
  PutawayType NVARCHAR(15),
  StackabilityCode NVARCHAR(10),
  ProductLife NVARCHAR(4),
  PercentAcceptableProductLife NVARCHAR(3),
  LpnsPerTier NVARCHAR(5),
  TiersPerPallet NVARCHAR(5),
  VelocityCode NVARCHAR(5),
  ReqBatchNbrFlg NVARCHAR(5),
  HarmonizedTariffCode NVARCHAR(255),
  HarmonizedTariffDescription NVARCHAR(150),
  Description3 NVARCHAR(255),
  HostAwareItemFlg NVARCHAR(5),
  UnNumber NVARCHAR(10),
  UnClass NVARCHAR(20),
  UnDescription NVARCHAR(150),
  HazardStatement NVARCHAR(100),
  ShippingTemperatureInstr NVARCHAR(50),
  PRIMARY KEY("PRODUCT")
);

CREATE TABLE wms_Vendor (
  createdAt TIMESTAMP,
  createdBy NVARCHAR(255),
  modifiedAt TIMESTAMP,
  modifiedBy NVARCHAR(255),
  BusinessPartnerIdSAP NVARCHAR(50) NOT NULL,
  VendorCode NVARCHAR(20),
  VendorName NVARCHAR(250),
  CustField1 NVARCHAR(25),
  PRIMARY KEY(BusinessPartnerIdSAP)
);

CREATE TABLE wms_PurchaseOrder (
  createdAt TIMESTAMP,
  createdBy NVARCHAR(255),
  modifiedAt TIMESTAMP,
  modifiedBy NVARCHAR(255),
  PurchaseOrder NVARCHAR(50) NOT NULL,
  BusinessPartnerIdSAP NVARCHAR(50),
  PoNbr NVARCHAR(30),
  FacilityCode NVARCHAR(20),
  VendorCode NVARCHAR(20),
  OrdDate DATE,
  RefNbr NVARCHAR(50),
  PoType NVARCHAR(50),
  DeliveryDate DATE,
  ShipDate DATE,
  CancelDate DATE,
  CustField1 NVARCHAR(50),
  CustField3 NVARCHAR(50),
  CustField4 NVARCHAR(50),
  CustField5 NVARCHAR(50),
  CustName NVARCHAR(50),
  CustAddr1 NVARCHAR(70),
  PRIMARY KEY(PurchaseOrder)
);

CREATE TABLE wms_PurchaseOrderItem (
  createdAt TIMESTAMP,
  createdBy NVARCHAR(255),
  modifiedAt TIMESTAMP,
  modifiedBy NVARCHAR(255),
  PurchaseOrderIdSap NVARCHAR(50) NOT NULL,
  SeqNbr NVARCHAR(9) NOT NULL,
  ProductIdSAP NVARCHAR(50),
  ItemPartA NVARCHAR(30),
  OrdQty DECIMAL(13, 3),
  CustField1 NVARCHAR(50),
  CustField2 NVARCHAR(50),
  to_PurchaseOrder_PurchaseOrder NVARCHAR(50),
  PRIMARY KEY(PurchaseOrderIdSap, SeqNbr)
);

CREATE TABLE wms_ASNHdrCompras (
  createdAt TIMESTAMP,
  createdBy NVARCHAR(255),
  modifiedAt TIMESTAMP,
  modifiedBy NVARCHAR(255),
  PurchaseOrderIdSap NVARCHAR(50) NOT NULL,
  BusinessPartnerIdSAP NVARCHAR(50),
  ShipmentNbr NVARCHAR(30),
  FacilityCode NVARCHAR(20),
  TrailerNbr NVARCHAR(30),
  ShipmentType NVARCHAR(20),
  VendorInfo NVARCHAR(30),
  ShippedDate NVARCHAR(14),
  CustField3 NVARCHAR(50),
  PRIMARY KEY(PurchaseOrderIdSap)
);

CREATE TABLE wms_ASNDtlCompras (
  createdAt TIMESTAMP,
  createdBy NVARCHAR(255),
  modifiedAt TIMESTAMP,
  modifiedBy NVARCHAR(255),
  PurchaseOrderIdSap NVARCHAR(50) NOT NULL,
  SeqNbr NVARCHAR(9) NOT NULL,
  ProductIdSAP NVARCHAR(50),
  ItemPartA NVARCHAR(30),
  ShippedQty DECIMAL(13, 3),
  PoNbr NVARCHAR(30),
  PoSeqNbr NVARCHAR(9),
  LpnLockCode NVARCHAR(15),
  to_ASNCompras_PurchaseOrderIdSap NVARCHAR(50),
  PRIMARY KEY(PurchaseOrderIdSap, SeqNbr)
);

CREATE TABLE wms_OrderHdr (
  createdAt TIMESTAMP,
  createdBy NVARCHAR(255),
  modifiedAt TIMESTAMP,
  modifiedBy NVARCHAR(255),
  order_nbr NVARCHAR(5000) NOT NULL,
  facility_code NVARCHAR(5000),
  company_code NVARCHAR(5000),
  order_type NVARCHAR(5000),
  ord_date SECONDDATE,
  req_ship_date SECONDDATE,
  cust_name NVARCHAR(5000),
  cust_addr NVARCHAR(5000),
  action_code NVARCHAR(5000),
  route_nbr NVARCHAR(5000),
  cust_city NVARCHAR(5000),
  cust_state NVARCHAR(5000),
  cust_country NVARCHAR(5000),
  cust_nbr NVARCHAR(5000),
  sales_channel NVARCHAR(5000),
  cust_field_1 NVARCHAR(5000),
  cust_field_2 NVARCHAR(5000),
  cust_field_3 NVARCHAR(5000),
  cust_field_4 NVARCHAR(5000),
  cust_field_5 NVARCHAR(5000),
  cust_date_1 SECONDDATE,
  cust_date_2 SECONDDATE,
  cust_short_text_1 NVARCHAR(5000),
  cust_short_text_2 NVARCHAR(5000),
  cust_short_text_3 NVARCHAR(5000),
  cust_short_text_4 NVARCHAR(5000),
  cust_short_text_5 NVARCHAR(5000),
  cust_long_text_1 NVARCHAR(5000),
  cust_long_text_2 NVARCHAR(5000),
  PRIMARY KEY(order_nbr)
);

CREATE TABLE wms_OrderDtl (
  createdAt TIMESTAMP,
  createdBy NVARCHAR(255),
  modifiedAt TIMESTAMP,
  modifiedBy NVARCHAR(255),
  po_nbr NVARCHAR(5000) NOT NULL,
  seq_nbr INTEGER NOT NULL,
  item_part_a NVARCHAR(5000),
  ord_qty DECIMAL(10, 3),
  action_code NVARCHAR(5000),
  cost DECIMAL(10, 2),
  sale_price DECIMAL(10, 8),
  cust_field_2 NVARCHAR(5000),
  cust_field_5 NVARCHAR(5000),
  order_order_nbr NVARCHAR(5000),
  PRIMARY KEY(po_nbr, seq_nbr)
);

CREATE VIEW ExchangeRate_ExchangeRate AS SELECT
  ExchangeRate_0.ExchangeRateType,
  ExchangeRate_0.SourceCurrency,
  ExchangeRate_0.TargetCurrency,
  ExchangeRate_0.ExchangeRateEffectiveDate,
  ExchangeRate_0.ExchangeRate
FROM global_finance_ExchangeRate AS ExchangeRate_0;

CREATE VIEW JournalEntryService_PreAsientoContable AS SELECT
  PreAsientoContable_0.PreAsientoContableId,
  PreAsientoContable_0.DocumentoCodigo,
  PreAsientoContable_0.NumeroDocumentoOrigen,
  PreAsientoContable_0.AccountingDocumentType,
  PreAsientoContable_0.CompanyCode,
  PreAsientoContable_0.DocumentDate,
  PreAsientoContable_0.PostingDate,
  PreAsientoContable_0.TransactionCurrency,
  PreAsientoContable_0.CompanyCodeCurrency,
  PreAsientoContable_0.GroupCurrency,
  PreAsientoContable_0.FreeDefinedCurrency,
  PreAsientoContable_0.CreatedByUser,
  PreAsientoContable_0.OriginalReferenceDocument,
  PreAsientoContable_0.OriginalReferenceDocumentLogicalSystem,
  PreAsientoContable_0.AccountingDocument,
  PreAsientoContable_0.DocumentReferenceID,
  PreAsientoContable_0.DocumentHeaderText,
  PreAsientoContable_0.ReversalReason,
  PreAsientoContable_0.ReversalReferenceDocument,
  PreAsientoContable_0.ReversalDate,
  PreAsientoContable_0.TaxReportingDate,
  PreAsientoContable_0.TaxDeterminationDate,
  PreAsientoContable_0.TaxFulfillmentDate,
  PreAsientoContable_0.DoTaxAmountCheck,
  PreAsientoContable_0.InvoiceReceiptDate,
  PreAsientoContable_0.ExchangeRateDate,
  PreAsientoContable_0.IndirectQuotedExchangeRate,
  PreAsientoContable_0.ExchangeRate,
  PreAsientoContable_0.SourceSystemCompanyCode,
  PreAsientoContable_0.SourceSystemAccountingDocument,
  PreAsientoContable_0.Reference1InDocumentHeader,
  PreAsientoContable_0.Reference2InDocumentHeader,
  PreAsientoContable_0.JrnlEntryCntrySpecificRef1,
  PreAsientoContable_0.JrnlEntryCntrySpecificDate1,
  PreAsientoContable_0.JrnlEntryCntrySpecificRef2,
  PreAsientoContable_0.JrnlEntryCntrySpecificDate2,
  PreAsientoContable_0.JrnlEntryCntrySpecificRef3,
  PreAsientoContable_0.JrnlEntryCntrySpecificDate3,
  PreAsientoContable_0.JrnlEntryCntrySpecificRef4,
  PreAsientoContable_0.JrnlEntryCntrySpecificDate4,
  PreAsientoContable_0.JrnlEntryCntrySpecificRef5,
  PreAsientoContable_0.JrnlEntryCntrySpecificDate5,
  PreAsientoContable_0.JrnlEntryCntrySpecificBp1,
  PreAsientoContable_0.JrnlEntryCntrySpecificBp2,
  PreAsientoContable_0.NroDocumentoSap,
  PreAsientoContable_0.FechaHoraCreacion,
  PreAsientoContable_0.Flujo,
  PreAsientoContable_0.to_Status_statusId
FROM JournalEntry_PreAsientoContable AS PreAsientoContable_0;

CREATE VIEW JournalEntryService_PreAsientoContableGLAccountItem AS SELECT
  PreAsientoContableGLAccountItem_0.PreAsientoContableGLAccountItemId,
  PreAsientoContableGLAccountItem_0.DocumentoCodigo,
  PreAsientoContableGLAccountItem_0.NumeroDocumentoOrigen,
  PreAsientoContableGLAccountItem_0.GlAccount,
  PreAsientoContableGLAccountItem_0.AmountInTransactionCurrency,
  PreAsientoContableGLAccountItem_0.ItemGroup,
  PreAsientoContableGLAccountItem_0.CompanyCode,
  PreAsientoContableGLAccountItem_0.AmountInCompanyCodeCurrency,
  PreAsientoContableGLAccountItem_0.AmountInGroupCurrency,
  PreAsientoContableGLAccountItem_0.AmountInFreeDefinedCurrency,
  PreAsientoContableGLAccountItem_0.DebitCreditCode,
  PreAsientoContableGLAccountItem_0.DocumentItemText,
  PreAsientoContableGLAccountItem_0.BusinessPlace,
  PreAsientoContableGLAccountItem_0.ReasonCode,
  PreAsientoContableGLAccountItem_0.AssignmentReference,
  PreAsientoContableGLAccountItem_0.OplAcctgDocItmCntrySpcfcRef,
  PreAsientoContableGLAccountItem_0.FinancialTransactionType,
  PreAsientoContableGLAccountItem_0.Plant,
  PreAsientoContableGLAccountItem_0.Material,
  PreAsientoContableGLAccountItem_0.QuantityInEntryUnit,
  PreAsientoContableGLAccountItem_0.UnitCode,
  PreAsientoContableGLAccountItem_0.IsNotCashDiscountLiable,
  PreAsientoContableGLAccountItem_0.TradingPartner,
  PreAsientoContableGLAccountItem_0.ValueDate,
  PreAsientoContableGLAccountItem_0.HouseBank,
  PreAsientoContableGLAccountItem_0.HouseBankAccount,
  PreAsientoContableGLAccountItem_0.Reference1IDByBusinessPartner,
  PreAsientoContableGLAccountItem_0.Reference2IDByBusinessPartner,
  PreAsientoContableGLAccountItem_0.Reference3IDByBusinessPartner,
  PreAsientoContableGLAccountItem_0.TaxCode,
  PreAsientoContableGLAccountItem_0.TaxJurisdiction,
  PreAsientoContableGLAccountItem_0.TaxItemGroup,
  PreAsientoContableGLAccountItem_0.TaxCountry,
  PreAsientoContableGLAccountItem_0.TaxExpenseAmountInTransCrcy,
  PreAsientoContableGLAccountItem_0.TaxExpenseAmountInCoCodeCrcy,
  PreAsientoContableGLAccountItem_0.TaxExpenseAmountInGroupCrcy,
  PreAsientoContableGLAccountItem_0.TaxExpenseAmountInFreeDefinedCrcy,
  PreAsientoContableGLAccountItem_0.AccountAssignmentType,
  PreAsientoContableGLAccountItem_0.AccAsgnProfitCenter,
  PreAsientoContableGLAccountItem_0.AccAsgnPartnerProfitCenter,
  PreAsientoContableGLAccountItem_0.AccAsgnSegment,
  PreAsientoContableGLAccountItem_0.AccAsgnPartnerSegment,
  PreAsientoContableGLAccountItem_0.AccAsgnCostCenter,
  PreAsientoContableGLAccountItem_0.AccAsgnCostCtrActivityType,
  PreAsientoContableGLAccountItem_0.AccAsgnWBSElement,
  PreAsientoContableGLAccountItem_0.AccAsgnMasterFixedAsset,
  PreAsientoContableGLAccountItem_0.AccAsgnFixedAsset,
  PreAsientoContableGLAccountItem_0.AccAsgnSalesOrder,
  PreAsientoContableGLAccountItem_0.AccAsgnSalesOrderItem,
  PreAsientoContableGLAccountItem_0.AccAsgnFunctionalArea,
  PreAsientoContableGLAccountItem_0.AccAsgnServiceDocType,
  PreAsientoContableGLAccountItem_0.AccAsgnServiceDocID,
  PreAsientoContableGLAccountItem_0.AccAsgnServiceDocItemID,
  PreAsientoContableGLAccountItem_0.AccAsgnWorkItem,
  PreAsientoContableGLAccountItem_0.ProfSuplCustomer,
  PreAsientoContableGLAccountItem_0.ProfSuplCustomerGroup,
  PreAsientoContableGLAccountItem_0.ProfSuplCustomerIndustry,
  PreAsientoContableGLAccountItem_0.ProfSuplCustomerCountry,
  PreAsientoContableGLAccountItem_0.ProfSuplSalesDistrict,
  PreAsientoContableGLAccountItem_0.ProfSuplSoldMaterial,
  PreAsientoContableGLAccountItem_0.ProfSuplSoldMaterialGroup,
  PreAsientoContableGLAccountItem_0.ProfSuplSalesOrganization,
  PreAsientoContableGLAccountItem_0.ProfSuplDistributionChannel,
  PreAsientoContableGLAccountItem_0.ProfSuplDivision,
  PreAsientoContableGLAccountItem_0.ProfSuplBillToParty,
  PreAsientoContableGLAccountItem_0.ProfSuplShipToParty,
  PreAsientoContableGLAccountItem_0.ProfSuplPersonnelNumber,
  PreAsientoContableGLAccountItem_0.ProfSuplWBSElement,
  PreAsientoContableGLAccountItem_0.ProfSuplFunctionalArea,
  PreAsientoContableGLAccountItem_0.ProfSuplServiceDocType,
  PreAsientoContableGLAccountItem_0.ProfSuplServiceDocID,
  PreAsientoContableGLAccountItem_0.ProfSuplServiceDocItemID,
  PreAsientoContableGLAccountItem_0.AddAtrPersonnelNumber,
  PreAsientoContableGLAccountItem_0.to_PreAsientoContable_PreAsientoContableId
FROM JournalEntry_PreAsientoContableGLAccountItem AS PreAsientoContableGLAccountItem_0;

CREATE VIEW JournalEntryService_PreAsientoContableCustomerAccountItem AS SELECT
  PreAsientoContableCustomerAccountItem_0.PreAsientoContableCustomerAccountItemId,
  PreAsientoContableCustomerAccountItem_0.DocumentoCodigo,
  PreAsientoContableCustomerAccountItem_0.NumeroDocumentoOrigen,
  PreAsientoContableCustomerAccountItem_0.Debtor,
  PreAsientoContableCustomerAccountItem_0.AmountInTransactionCurrency,
  PreAsientoContableCustomerAccountItem_0.AmountInCompanyCodeCurrency,
  PreAsientoContableCustomerAccountItem_0.AmountInGroupCurrency,
  PreAsientoContableCustomerAccountItem_0.AmountInFreeDefinedCurrency,
  PreAsientoContableCustomerAccountItem_0.DebitCreditCode,
  PreAsientoContableCustomerAccountItem_0.AltvRecnclnAccts,
  PreAsientoContableCustomerAccountItem_0.ReportingCountry,
  PreAsientoContableCustomerAccountItem_0.DocumentItemText,
  PreAsientoContableCustomerAccountItem_0.AssignmentReference,
  PreAsientoContableCustomerAccountItem_0.OplAcctgDocItmCntrySpcfcRef,
  PreAsientoContableCustomerAccountItem_0.Reference1IDByBusinessPartner,
  PreAsientoContableCustomerAccountItem_0.Reference2IDByBusinessPartner,
  PreAsientoContableCustomerAccountItem_0.Reference3IDByBusinessPartner,
  PreAsientoContableCustomerAccountItem_0.CreditControlArea,
  PreAsientoContableCustomerAccountItem_0.StateCentralBankPaymentReason,
  PreAsientoContableCustomerAccountItem_0.VatRegistration,
  PreAsientoContableCustomerAccountItem_0.BranchAccount,
  PreAsientoContableCustomerAccountItem_0.BusinessPlace,
  PreAsientoContableCustomerAccountItem_0.TaxCountry,
  PreAsientoContableCustomerAccountItem_0.HouseBank,
  PreAsientoContableCustomerAccountItem_0.HouseBankAccount,
  PreAsientoContableCustomerAccountItem_0.JointVentureBillingType,
  PreAsientoContableCustomerAccountItem_0.DueCalculationBaseDate,
  PreAsientoContableCustomerAccountItem_0.CashDiscountBaseAmount,
  PreAsientoContableCustomerAccountItem_0.CashDiscount1Days,
  PreAsientoContableCustomerAccountItem_0.CashDiscount1Percent,
  PreAsientoContableCustomerAccountItem_0.CashDiscount2Days,
  PreAsientoContableCustomerAccountItem_0.CashDiscount2Percent,
  PreAsientoContableCustomerAccountItem_0.NetPaymentDays,
  PreAsientoContableCustomerAccountItem_0.PaymentMethod,
  PreAsientoContableCustomerAccountItem_0.PaymentReason,
  PreAsientoContableCustomerAccountItem_0.PaymentBlockingReason,
  PreAsientoContableCustomerAccountItem_0.PaymentServiceProvider,
  PreAsientoContableCustomerAccountItem_0.PaymentByPaymentServicePrvdr,
  PreAsientoContableCustomerAccountItem_0.SpecialGLCode,
  PreAsientoContableCustomerAccountItem_0.TaxCode,
  PreAsientoContableCustomerAccountItem_0.TaxJurisdiction,
  PreAsientoContableCustomerAccountItem_0.TaxItemGroup,
  PreAsientoContableCustomerAccountItem_0.OneTimeCustName,
  PreAsientoContableCustomerAccountItem_0.OneTimeCustCityName,
  PreAsientoContableCustomerAccountItem_0.OneTimeCustCountry,
  PreAsientoContableCustomerAccountItem_0.OneTimeCustBankCountry,
  PreAsientoContableCustomerAccountItem_0.OneTimeCustBankAccount,
  PreAsientoContableCustomerAccountItem_0.OneTimeCustBankControlKey,
  PreAsientoContableCustomerAccountItem_0.OneTimeCustBankNumber,
  PreAsientoContableCustomerAccountItem_0.OneTimeCustTaxNumber1,
  PreAsientoContableCustomerAccountItem_0.OneTimeCustTaxNumber2,
  PreAsientoContableCustomerAccountItem_0.OneTimeCustTaxNumber3,
  PreAsientoContableCustomerAccountItem_0.OneTimeCustTaxNumber4,
  PreAsientoContableCustomerAccountItem_0.OneTimeCustTaxNumber5,
  PreAsientoContableCustomerAccountItem_0.OneTimeCustIsNaturalPerson,
  PreAsientoContableCustomerAccountItem_0.OneTimeCustRegion,
  PreAsientoContableCustomerAccountItem_0.OneTimeCustVATLiability,
  PreAsientoContableCustomerAccountItem_0.OneTimeCustTaxNumberType,
  PreAsientoContableCustomerAccountItem_0.to_PreAsientoContable_PreAsientoContableId
FROM JournalEntry_PreAsientoContableCustomerAccountItem AS PreAsientoContableCustomerAccountItem_0;

CREATE VIEW JournalEntryService_PreAsientoContableSupplierAccountItem AS SELECT
  PreAsientoContableSupplierAccountItem_0.PreAsientoContableSupplierAccountItemId,
  PreAsientoContableSupplierAccountItem_0.DocumentoCodigo,
  PreAsientoContableSupplierAccountItem_0.NumeroDocumentoOrigen,
  PreAsientoContableSupplierAccountItem_0.Creditor,
  PreAsientoContableSupplierAccountItem_0.AmountInTransactionCurrency,
  PreAsientoContableSupplierAccountItem_0.AmountInCompanyCodeCurrency,
  PreAsientoContableSupplierAccountItem_0.AmountInGroupCurrency,
  PreAsientoContableSupplierAccountItem_0.AmountInFreeDefinedCurrency,
  PreAsientoContableSupplierAccountItem_0.DebitCreditCode,
  PreAsientoContableSupplierAccountItem_0.AltvRecnclnAccts,
  PreAsientoContableSupplierAccountItem_0.DocumentItemText,
  PreAsientoContableSupplierAccountItem_0.AssignmentReference,
  PreAsientoContableSupplierAccountItem_0.OplAcctgDocItmCntrySpcfcRef,
  PreAsientoContableSupplierAccountItem_0.Reference1IDByBusinessPartner,
  PreAsientoContableSupplierAccountItem_0.Reference2IDByBusinessPartner,
  PreAsientoContableSupplierAccountItem_0.Reference3IDByBusinessPartner,
  PreAsientoContableSupplierAccountItem_0.StateCentralBankPaymentReason,
  PreAsientoContableSupplierAccountItem_0.BranchAccount,
  PreAsientoContableSupplierAccountItem_0.BusinessPlace,
  PreAsientoContableSupplierAccountItem_0.TaxCountry,
  PreAsientoContableSupplierAccountItem_0.HouseBank,
  PreAsientoContableSupplierAccountItem_0.HouseBankAccount,
  PreAsientoContableSupplierAccountItem_0.DueCalculationBaseDate,
  PreAsientoContableSupplierAccountItem_0.CashDiscountBaseAmount,
  PreAsientoContableSupplierAccountItem_0.CashDiscount1Days,
  PreAsientoContableSupplierAccountItem_0.CashDiscount1Percent,
  PreAsientoContableSupplierAccountItem_0.CashDiscount2Days,
  PreAsientoContableSupplierAccountItem_0.CashDiscount2Percent,
  PreAsientoContableSupplierAccountItem_0.NetPaymentDays,
  PreAsientoContableSupplierAccountItem_0.PaymentMethod,
  PreAsientoContableSupplierAccountItem_0.PaymentReason,
  PreAsientoContableSupplierAccountItem_0.PaymentBlockingReason,
  PreAsientoContableSupplierAccountItem_0.AlternativePayee,
  PreAsientoContableSupplierAccountItem_0.PayeeCountry,
  PreAsientoContableSupplierAccountItem_0.PayeeBankNumber,
  PreAsientoContableSupplierAccountItem_0.PayeeSWIFTCode,
  PreAsientoContableSupplierAccountItem_0.PayeeBankAccount,
  PreAsientoContableSupplierAccountItem_0.PayeeIBAN,
  PreAsientoContableSupplierAccountItem_0.PayeeBankAccountHolderName,
  PreAsientoContableSupplierAccountItem_0.SpecialGLCode,
  PreAsientoContableSupplierAccountItem_0.TaxCode,
  PreAsientoContableSupplierAccountItem_0.TaxJurisdiction,
  PreAsientoContableSupplierAccountItem_0.TaxItemGroup,
  PreAsientoContableSupplierAccountItem_0.OneTimeVendorName,
  PreAsientoContableSupplierAccountItem_0.OneTimeVendorCityName,
  PreAsientoContableSupplierAccountItem_0.OneTimeVendorCountry,
  PreAsientoContableSupplierAccountItem_0.to_PreAsientoContable_PreAsientoContableId
FROM JournalEntry_PreAsientoContableSupplierAccountItem AS PreAsientoContableSupplierAccountItem_0;

CREATE VIEW JournalEntryService_PreAsientoContableTaxAccountItem AS SELECT
  PreAsientoContableTaxAccountItem_0.PreAsientoContableTaxAccountItemId,
  PreAsientoContableTaxAccountItem_0.DocumentoCodigo,
  PreAsientoContableTaxAccountItem_0.NumeroDocumentoOrigen,
  PreAsientoContableTaxAccountItem_0.TaxCode,
  PreAsientoContableTaxAccountItem_0.AmountInTransactionCurrency,
  PreAsientoContableTaxAccountItem_0.TaxItemClassification,
  PreAsientoContableTaxAccountItem_0.ConditionType,
  PreAsientoContableTaxAccountItem_0.TaxJurisdiction,
  PreAsientoContableTaxAccountItem_0.TaxJurisdictionLevel,
  PreAsientoContableTaxAccountItem_0.LowestLevelTaxJurisdiction,
  PreAsientoContableTaxAccountItem_0.TaxItemGroup,
  PreAsientoContableTaxAccountItem_0.TaxCountry,
  PreAsientoContableTaxAccountItem_0.TaxRate,
  PreAsientoContableTaxAccountItem_0.TaxDeterminationDate,
  PreAsientoContableTaxAccountItem_0.IsDirectTaxPosting,
  PreAsientoContableTaxAccountItem_0.AmountInCompanyCodeCurrency,
  PreAsientoContableTaxAccountItem_0.AmountInGroupCurrency,
  PreAsientoContableTaxAccountItem_0.AmountInFreeDefinedCurrency,
  PreAsientoContableTaxAccountItem_0.DebitCreditCode,
  PreAsientoContableTaxAccountItem_0.ProductiveTaxText,
  PreAsientoContableTaxAccountItem_0.TaxBaseAmountInTransCrcy,
  PreAsientoContableTaxAccountItem_0.TaxBaseAmountInCoCodeCrcy,
  PreAsientoContableTaxAccountItem_0.TaxBaseAmountInGroupCrcy,
  PreAsientoContableTaxAccountItem_0.TaxBaseAmountInFreeDefinedCrcy,
  PreAsientoContableTaxAccountItem_0.to_PreAsientoContable_PreAsientoContableId
FROM JournalEntry_PreAsientoContableTaxAccountItem AS PreAsientoContableTaxAccountItem_0;

CREATE VIEW JournalEntryService_PreAsientoContableWithholdingTaxAccountItem AS SELECT
  PreAsientoContableWithholdingTaxAccountItem_0.PreAsientoContableWithholdingTaxAccountItemId,
  PreAsientoContableWithholdingTaxAccountItem_0.DocumentoCodigo,
  PreAsientoContableWithholdingTaxAccountItem_0.NumeroDocumentoOrigen,
  PreAsientoContableWithholdingTaxAccountItem_0.WithholdingTaxType,
  PreAsientoContableWithholdingTaxAccountItem_0.WithholdingTaxCode,
  PreAsientoContableWithholdingTaxAccountItem_0.TaxBaseAmountInTransCrcy,
  PreAsientoContableWithholdingTaxAccountItem_0.AmountInTransactionCurrency,
  PreAsientoContableWithholdingTaxAccountItem_0.AmountInCompanyCodeCurrency,
  PreAsientoContableWithholdingTaxAccountItem_0.AmountInGroupCurrency,
  PreAsientoContableWithholdingTaxAccountItem_0.AmountInFreeDefinedCurrency,
  PreAsientoContableWithholdingTaxAccountItem_0.TaxBaseAmountInCoCodeCrcy,
  PreAsientoContableWithholdingTaxAccountItem_0.TaxBaseAmountInGroupCrcy,
  PreAsientoContableWithholdingTaxAccountItem_0.TaxBaseAmountInFreeDefinedCrcy,
  PreAsientoContableWithholdingTaxAccountItem_0.TaxIsToBeCalculated,
  PreAsientoContableWithholdingTaxAccountItem_0.to_PreAsientoContable_PreAsientoContableId
FROM JournalEntry_PreAsientoContableWithholdingTaxAccountItem AS PreAsientoContableWithholdingTaxAccountItem_0;

CREATE VIEW JournalEntryService_PreAsientoContableLog AS SELECT
  PreAsientoContableLog_0.PreAsientoContableLogId,
  PreAsientoContableLog_0.NroDocumentoOrigen,
  PreAsientoContableLog_0.DocumentoCodigo,
  PreAsientoContableLog_0.Accion,
  PreAsientoContableLog_0.Mensaje,
  PreAsientoContableLog_0.Comentario,
  PreAsientoContableLog_0.Usuario,
  PreAsientoContableLog_0.FechaHora,
  PreAsientoContableLog_0.to_PreAsientoContable_PreAsientoContableId
FROM JournalEntry_PreAsientoContableLog AS PreAsientoContableLog_0;

CREATE VIEW JournalEntry_ViewPreAsientoContable AS SELECT
  PreAsientoContable_0.PreAsientoContableId,
  PreAsientoContable_0.DocumentoCodigo,
  PreAsientoContable_0.NumeroDocumentoOrigen,
  PreAsientoContable_0.AccountingDocumentType,
  PreAsientoContable_0.CompanyCode,
  PreAsientoContable_0.DocumentDate,
  PreAsientoContable_0.PostingDate,
  PreAsientoContable_0.TransactionCurrency,
  PreAsientoContable_0.CompanyCodeCurrency,
  PreAsientoContable_0.GroupCurrency,
  PreAsientoContable_0.FreeDefinedCurrency,
  PreAsientoContable_0.CreatedByUser,
  PreAsientoContable_0.OriginalReferenceDocument,
  PreAsientoContable_0.OriginalReferenceDocumentLogicalSystem,
  PreAsientoContable_0.AccountingDocument,
  PreAsientoContable_0.DocumentReferenceID,
  PreAsientoContable_0.DocumentHeaderText,
  PreAsientoContable_0.ReversalReason,
  PreAsientoContable_0.ReversalReferenceDocument,
  PreAsientoContable_0.ReversalDate,
  PreAsientoContable_0.TaxReportingDate,
  PreAsientoContable_0.TaxDeterminationDate,
  PreAsientoContable_0.TaxFulfillmentDate,
  PreAsientoContable_0.DoTaxAmountCheck,
  PreAsientoContable_0.InvoiceReceiptDate,
  PreAsientoContable_0.ExchangeRateDate,
  PreAsientoContable_0.IndirectQuotedExchangeRate,
  PreAsientoContable_0.ExchangeRate,
  PreAsientoContable_0.SourceSystemCompanyCode,
  PreAsientoContable_0.SourceSystemAccountingDocument,
  PreAsientoContable_0.Reference1InDocumentHeader,
  PreAsientoContable_0.Reference2InDocumentHeader,
  PreAsientoContable_0.JrnlEntryCntrySpecificRef1,
  PreAsientoContable_0.JrnlEntryCntrySpecificDate1,
  PreAsientoContable_0.JrnlEntryCntrySpecificRef2,
  PreAsientoContable_0.JrnlEntryCntrySpecificDate2,
  PreAsientoContable_0.JrnlEntryCntrySpecificRef3,
  PreAsientoContable_0.JrnlEntryCntrySpecificDate3,
  PreAsientoContable_0.JrnlEntryCntrySpecificRef4,
  PreAsientoContable_0.JrnlEntryCntrySpecificDate4,
  PreAsientoContable_0.JrnlEntryCntrySpecificRef5,
  PreAsientoContable_0.JrnlEntryCntrySpecificDate5,
  PreAsientoContable_0.JrnlEntryCntrySpecificBp1,
  PreAsientoContable_0.JrnlEntryCntrySpecificBp2,
  PreAsientoContable_0.NroDocumentoSap,
  PreAsientoContable_0.FechaHoraCreacion,
  to_Status_1.statusDescription AS StatusName,
  PreAsientoContable_0.to_Status_statusId AS StatusId,
  PreAsientoContable_0.Flujo
FROM (JournalEntry_PreAsientoContable AS PreAsientoContable_0 LEFT JOIN master_data_MasterDataStatus AS to_Status_1 ON PreAsientoContable_0.to_Status_statusId = to_Status_1.statusId);

CREATE VIEW LetrasService_Planilla AS SELECT
  Planilla_0.ID,
  Planilla_0.createdAt,
  Planilla_0.createdBy,
  Planilla_0.modifiedAt,
  Planilla_0.modifiedBy,
  Planilla_0.NroLetras,
  Planilla_0.Planilla,
  Planilla_0.ImporteTotal,
  Planilla_0.ImporteDolares,
  Planilla_0.Moneda,
  Planilla_0.Customer,
  Planilla_0.Banco_ID,
  Planilla_0.ExchangeRate,
  Planilla_0.ExchangeRateDate,
  Planilla_0.Sequence,
  Planilla_0.Sociedad_companyCode,
  Planilla_0.EstadoPlanilla_Codigo
FROM Letras_Planilla AS Planilla_0;

CREATE VIEW LetrasService_Banco AS SELECT
  Banco_0.ID,
  Banco_0.createdAt,
  Banco_0.createdBy,
  Banco_0.modifiedAt,
  Banco_0.modifiedBy,
  Banco_0.Codigo,
  Banco_0.Nombre
FROM Letras_Banco AS Banco_0;

CREATE VIEW Letras_Company AS SELECT
  Company_0.companyCode,
  Company_0.companyCodeName,
  Company_0.cityName,
  Company_0.country,
  Company_0.currency,
  Company_0."LANGUAGE",
  Company_0.company,
  Company_0.creditControlArea,
  Company_0.extendedWhldgTaxIsActive,
  Company_0.companyLogo,
  Company_0.companyIdentification,
  Company_0.companyPrincipalAddress
FROM master_data_Company AS Company_0;

CREATE VIEW LetrasService_EstadoPlanilla AS SELECT
  EstadoPlanilla_0.Codigo,
  EstadoPlanilla_0.Descripcion
FROM Letras_EstadoPlanilla AS EstadoPlanilla_0;

CREATE VIEW LetrasService_Letras AS SELECT
  Letras_0.ID,
  Letras_0.createdAt,
  Letras_0.createdBy,
  Letras_0.modifiedAt,
  Letras_0.modifiedBy,
  Letras_0.Code,
  Letras_0.Sequence,
  Letras_0.Documento,
  Letras_0.Serie,
  Letras_0.Numero,
  Letras_0.CodigoMoneda,
  Letras_0.FechaEmision,
  Letras_0.Dias,
  Letras_0.FechaVencimiento,
  Letras_0.TipoCambio,
  Letras_0.Referencia,
  Letras_0.TotalMonedaDocumento,
  Letras_0.TotalDolares,
  Letras_0.Vendedor,
  Letras_0.CodigoJournalEntry,
  Letras_0.JournalEntryItem,
  Letras_0.FiscalYear,
  Letras_0.EstadoLetras_Codigo,
  Letras_0.Planilla_ID,
  Letras_0.TipoLetra_Codigo
FROM Letras_Letras AS Letras_0;

CREATE VIEW LetrasService_EstadoLetras AS SELECT
  EstadoLetras_0.Codigo,
  EstadoLetras_0.Descripcion
FROM Letras_EstadoLetras AS EstadoLetras_0;

CREATE VIEW LetrasService_TipoLetra AS SELECT
  TipoLetra_0.Codigo,
  TipoLetra_0.Descripcion,
  TipoLetra_0.GlAccount
FROM Letras_TipoLetra AS TipoLetra_0;

CREATE VIEW LetrasService_CuentasPorCobrar AS SELECT
  CuentaPorCobrar_0.ID,
  CuentaPorCobrar_0.createdAt,
  CuentaPorCobrar_0.createdBy,
  CuentaPorCobrar_0.modifiedAt,
  CuentaPorCobrar_0.modifiedBy,
  CuentaPorCobrar_0.Planilla_ID,
  CuentaPorCobrar_0.SourceLedger,
  CuentaPorCobrar_0.CompanyCode,
  CuentaPorCobrar_0.FiscalYear,
  CuentaPorCobrar_0.AccountingDocument,
  CuentaPorCobrar_0.LedgerGLLineItem,
  CuentaPorCobrar_0.Ledger,
  CuentaPorCobrar_0.CompanyCodeName,
  CuentaPorCobrar_0.AccountingDocumentType,
  CuentaPorCobrar_0.NetDueDate,
  CuentaPorCobrar_0.Customer,
  CuentaPorCobrar_0.CustomerTaxNumber1,
  CuentaPorCobrar_0.CustomerHouseBank,
  CuentaPorCobrar_0.TaxNumberType,
  CuentaPorCobrar_0.CustomerFullName,
  CuentaPorCobrar_0.ClearingDate,
  CuentaPorCobrar_0.ClearingAccountingDocumentType,
  CuentaPorCobrar_0.ClearingJournalEntry,
  CuentaPorCobrar_0.DocumentReferenceID,
  CuentaPorCobrar_0.ReferenceDocument,
  CuentaPorCobrar_0.DocumentDate,
  CuentaPorCobrar_0.TransactionCurrency,
  CuentaPorCobrar_0.HouseBank,
  CuentaPorCobrar_0.HouseBankAccount,
  CuentaPorCobrar_0.BalanceTransactionCurrency,
  CuentaPorCobrar_0.AmountInBalanceTransacCrcy,
  CuentaPorCobrar_0.GLAccount,
  CuentaPorCobrar_0.IsReversal,
  CuentaPorCobrar_0.IsReversed,
  CuentaPorCobrar_0.DocumentItemText,
  CuentaPorCobrar_0.FinancialAccountType,
  CuentaPorCobrar_0.ReversalReferenceDocumentCntxt,
  CuentaPorCobrar_0.ReversalReferenceDocument,
  CuentaPorCobrar_0.EstadoCobranzaValue,
  CuentaPorCobrar_0.EstadoCobranzaDescription,
  CuentaPorCobrar_0.BillToParty,
  CuentaPorCobrar_0.EstadoFacturacionValue,
  CuentaPorCobrar_0.EstadoFacturacionDescription,
  CuentaPorCobrar_0.AmountInCompanyCodeCurrency,
  CuentaPorCobrar_0.AmountInGlobalCurrency,
  CuentaPorCobrar_0.AmountInTransactionCurrency,
  CuentaPorCobrar_0.CompanyCodeCurrency,
  CuentaPorCobrar_0.GlobalCurrency,
  CuentaPorCobrar_0.BusinessPartnerIDByExtSystem,
  CuentaPorCobrar_0.PostingDate,
  CuentaPorCobrar_0.IndEliminado,
  CuentaPorCobrar_0.IndRefinanciado
FROM Letras_CuentaPorCobrar AS CuentaPorCobrar_0;

CREATE VIEW LetrasService_PlanillaLog AS SELECT
  PlanillaLog_0.ID,
  PlanillaLog_0.createdAt,
  PlanillaLog_0.createdBy,
  PlanillaLog_0.modifiedAt,
  PlanillaLog_0.modifiedBy,
  PlanillaLog_0.Evento,
  PlanillaLog_0.Detalle,
  PlanillaLog_0.Planilla_ID
FROM Letras_PlanillaLog AS PlanillaLog_0;

CREATE VIEW LetrasService_LetrasLog AS SELECT
  LetrasLog_0.ID,
  LetrasLog_0.createdAt,
  LetrasLog_0.createdBy,
  LetrasLog_0.modifiedAt,
  LetrasLog_0.modifiedBy,
  LetrasLog_0.Evento,
  LetrasLog_0.Detalle,
  LetrasLog_0.Letras_ID
FROM Letras_LetrasLog AS LetrasLog_0;

CREATE VIEW Letras_Currency AS SELECT
  Currency_0.CurrencyCode,
  Currency_0.CurrencyName,
  Currency_0.CurrencySymbol
FROM master_data_Currency AS Currency_0;

CREATE VIEW Letras_ViewPlanilla AS SELECT
  Planilla_0.ID,
  Planilla_0.createdAt,
  Planilla_0.createdBy,
  Planilla_0.modifiedAt,
  Planilla_0.modifiedBy,
  Planilla_0.NroLetras,
  Planilla_0.Planilla,
  Planilla_0.ImporteTotal,
  Planilla_0.Moneda,
  Banco_1.Codigo AS BancoCodigo,
  Banco_1.Nombre AS BancoNombre,
  Planilla_0.Sociedad_companyCode AS CompanyCode,
  Sociedad_2.companyCodeName AS CompanyName,
  Planilla_0.EstadoPlanilla_Codigo AS EstadoPlanillaCode,
  EstadoPlanilla_3.Descripcion AS EstadoPlanillaName
FROM (((Letras_Planilla AS Planilla_0 LEFT JOIN Letras_Banco AS Banco_1 ON Planilla_0.Banco_ID = Banco_1.ID) LEFT JOIN master_data_Company AS Sociedad_2 ON Planilla_0.Sociedad_companyCode = Sociedad_2.companyCode) LEFT JOIN Letras_EstadoPlanilla AS EstadoPlanilla_3 ON Planilla_0.EstadoPlanilla_Codigo = EstadoPlanilla_3.Codigo);

CREATE VIEW Letras_LetrasCube AS SELECT
  Letras_0.ID,
  Letras_0.createdAt,
  Letras_0.createdBy,
  Letras_0.modifiedAt,
  Letras_0.modifiedBy,
  Letras_0.Code,
  Letras_0.Sequence,
  Letras_0.Documento,
  Letras_0.Serie,
  Letras_0.Numero,
  Letras_0.CodigoMoneda,
  Letras_0.FechaEmision,
  Letras_0.Dias,
  Letras_0.FechaVencimiento,
  Letras_0.TipoCambio,
  Letras_0.Referencia,
  Letras_0.TotalMonedaDocumento,
  Letras_0.TotalDolares,
  Letras_0.Vendedor,
  Letras_0.CodigoJournalEntry,
  Letras_0.JournalEntryItem,
  Letras_0.FiscalYear,
  Letras_0.EstadoLetras_Codigo,
  Letras_0.Planilla_ID,
  Letras_0.TipoLetra_Codigo,
  Letras_0.TipoLetra_Codigo || ' (' || TipoLetra_2.Descripcion || ')' AS TipoLetraComposition,
  Letras_0.EstadoLetras_Codigo || ' (' || EstadoLetras_1.Descripcion || ')' AS EstadoLetraComposition
FROM ((Letras_Letras AS Letras_0 LEFT JOIN Letras_EstadoLetras AS EstadoLetras_1 ON Letras_0.EstadoLetras_Codigo = EstadoLetras_1.Codigo) LEFT JOIN Letras_TipoLetra AS TipoLetra_2 ON Letras_0.TipoLetra_Codigo = TipoLetra_2.Codigo);

CREATE VIEW MasterDataService_GlobalSetting AS SELECT
  GlobalSetting_0.createdAt,
  GlobalSetting_0.createdBy,
  GlobalSetting_0.modifiedAt,
  GlobalSetting_0.modifiedBy,
  GlobalSetting_0.GlobalSettingId,
  GlobalSetting_0.GlobalSettingModule,
  GlobalSetting_0.GlobalSettingType,
  GlobalSetting_0.GlobalSettingName,
  GlobalSetting_0.GlobalSettingClassification,
  GlobalSetting_0.GlobalSettingCode,
  GlobalSetting_0.GlobalSettingValue,
  GlobalSetting_0.GlobalSettingValue2,
  GlobalSetting_0.GlobalSettingValue3,
  GlobalSetting_0.GlobalSettingValue4,
  GlobalSetting_0.GlobalSettingValue5,
  GlobalSetting_0.GlobalSettingDescription,
  GlobalSetting_0.GlobalSettingPatternId,
  GlobalSetting_0.GlobalSettingStatus,
  GlobalSetting_0.GlobalSettingIsEditable,
  GlobalSetting_0.GlobalSettingIsDeletable,
  GlobalSetting_0.GlobalSettingIsBlocked,
  GlobalSetting_0.terminal
FROM master_data_GlobalSetting AS GlobalSetting_0;

CREATE VIEW master_data_ViewGlobalSettingPatterns AS SELECT
  GlobalSetting_0.createdAt,
  GlobalSetting_0.createdBy,
  GlobalSetting_0.modifiedAt,
  GlobalSetting_0.modifiedBy,
  GlobalSetting_0.GlobalSettingId,
  GlobalSetting_0.GlobalSettingModule,
  GlobalSetting_0.GlobalSettingType,
  GlobalSetting_0.GlobalSettingName,
  GlobalSetting_0.GlobalSettingClassification,
  GlobalSetting_0.GlobalSettingCode,
  GlobalSetting_0.GlobalSettingValue,
  GlobalSetting_0.GlobalSettingValue2,
  GlobalSetting_0.GlobalSettingValue3,
  GlobalSetting_0.GlobalSettingValue4,
  GlobalSetting_0.GlobalSettingValue5,
  GlobalSetting_0.GlobalSettingDescription,
  GlobalSetting_0.GlobalSettingPatternId,
  GlobalSetting_0.GlobalSettingStatus,
  GlobalSetting_0.GlobalSettingIsEditable,
  GlobalSetting_0.GlobalSettingIsDeletable,
  GlobalSetting_0.GlobalSettingIsBlocked,
  GlobalSetting_0.terminal
FROM master_data_GlobalSetting AS GlobalSetting_0
WHERE GlobalSetting_0.GlobalSettingClassification = 'PATTERN';

CREATE VIEW master_data_Types AS SELECT
  GlobalSetting_0.GlobalSettingType
FROM master_data_GlobalSetting AS GlobalSetting_0
WHERE GlobalSetting_0.GlobalSettingType IS NOT NULL
GROUP BY GlobalSetting_0.GlobalSettingType;

CREATE VIEW master_data_Modules AS SELECT
  GlobalSetting_0.GlobalSettingModule
FROM master_data_GlobalSetting AS GlobalSetting_0
WHERE GlobalSetting_0.GlobalSettingModule IS NOT NULL
GROUP BY GlobalSetting_0.GlobalSettingModule;

CREATE VIEW MasterDataService_Currency AS SELECT
  Currency_0.CurrencyCode,
  Currency_0.CurrencyName,
  Currency_0.CurrencySymbol
FROM master_data_Currency AS Currency_0;

CREATE VIEW QueueService_Queue AS SELECT
  Queue_0.createdAt,
  Queue_0.createdBy,
  Queue_0.modifiedAt,
  Queue_0.modifiedBy,
  Queue_0.ID,
  Queue_0.EventType,
  Queue_0.Status,
  Queue_0.ProcessedAt,
  Queue_0.Priority,
  Queue_0.RetryCount,
  Queue_0.RetryMax,
  Queue_0.Payload,
  Queue_0.PayloadHash,
  Queue_0.ErrorMessage,
  Queue_0.CorrelationId,
  Queue_0.ObjectId
FROM queue_Queue AS Queue_0;

CREATE VIEW TrazabilidadService_EventType AS SELECT
  EventType_0.Code,
  EventType_0.Name,
  EventType_0.Description,
  EventType_0.Enable,
  EventType_0.to_OriginSystem_Code,
  EventType_0.to_TargetSystem_Code
FROM trazabilidad_EventType AS EventType_0;

CREATE VIEW TrazabilidadService_System AS SELECT
  System_0.Code,
  System_0.Name
FROM trazabilidad_System AS System_0;

CREATE VIEW TrazabilidadService_Status AS SELECT
  Status_0.Code,
  Status_0.Name,
  Status_0.Color,
  Status_0.Description
FROM trazabilidad_Status AS Status_0;

CREATE VIEW TrazabilidadService_RequestType AS SELECT
  RequestType_0.Code,
  RequestType_0.Name
FROM trazabilidad_RequestType AS RequestType_0;

CREATE VIEW TrazabilidadService_MethodType AS SELECT
  MethodType_0.Code,
  MethodType_0.Name
FROM trazabilidad_MethodType AS MethodType_0;

CREATE VIEW trazabilidad_EventView AS SELECT
  Event_0.ID,
  Event_0.EventInitDateTime,
  Event_0.EventFinishDateTime,
  Event_0.to_EventType_Code,
  Event_0.to_Status_Code
FROM trazabilidad_Event AS Event_0;

CREATE VIEW TrazabilidadService_EventDetail AS SELECT
  EventDetail_0.ID,
  EventDetail_0.Url,
  EventDetail_0.StartDateTime,
  EventDetail_0.EndDateTime,
  EventDetail_0.RequestContent,
  EventDetail_0.ResponseContent,
  EventDetail_0.ErrorMessage,
  EventDetail_0.AttemptNumber,
  EventDetail_0.to_Event_ID,
  EventDetail_0.to_OriginSystem_Code,
  EventDetail_0.to_TargetSystem_Code,
  EventDetail_0.to_Status_Code,
  EventDetail_0.to_Action_Code,
  EventDetail_0.to_Method_Code,
  EventDetail_0.to_RequestType_Code
FROM trazabilidad_EventDetail AS EventDetail_0;

CREATE VIEW WMSService_ItemAndBarcode AS SELECT
  ItemAndBarcode_0.createdAt,
  ItemAndBarcode_0.createdBy,
  ItemAndBarcode_0.modifiedAt,
  ItemAndBarcode_0.modifiedBy,
  ItemAndBarcode_0."PRODUCT",
  ItemAndBarcode_0.PartA,
  ItemAndBarcode_0.DescriptionItem,
  ItemAndBarcode_0.Barcode,
  ItemAndBarcode_0.UnitCost,
  ItemAndBarcode_0.UnitLenght,
  ItemAndBarcode_0.UnitWidth,
  ItemAndBarcode_0.UnitHeight,
  ItemAndBarcode_0.UnitWeight,
  ItemAndBarcode_0.UnitVolume,
  ItemAndBarcode_0.SeasonCode,
  ItemAndBarcode_0.BrandCode,
  ItemAndBarcode_0.CustAttr1,
  ItemAndBarcode_0.RetailPrice,
  ItemAndBarcode_0.NetCost,
  ItemAndBarcode_0.CurrencyCode,
  ItemAndBarcode_0.BarcodePack,
  ItemAndBarcode_0.StdPackQty,
  ItemAndBarcode_0.StdPackLength,
  ItemAndBarcode_0.StdPackWidth,
  ItemAndBarcode_0.StdPackHeight,
  ItemAndBarcode_0.StdPackWeight,
  ItemAndBarcode_0.StdPackVolume,
  ItemAndBarcode_0.BarcodeCase,
  ItemAndBarcode_0.StdCaseQty,
  ItemAndBarcode_0.MaxCaseQty,
  ItemAndBarcode_0.StdCaseLength,
  ItemAndBarcode_0.StdCaseWidth,
  ItemAndBarcode_0.StdCaseHeight,
  ItemAndBarcode_0.StdCaseWeight,
  ItemAndBarcode_0.StdCaseVolume,
  ItemAndBarcode_0.Dimension1,
  ItemAndBarcode_0.Dimension2,
  ItemAndBarcode_0.Dimension3,
  ItemAndBarcode_0.Hierarchy1Code,
  ItemAndBarcode_0.Hierarchy1Description,
  ItemAndBarcode_0.Hierarchy2Code,
  ItemAndBarcode_0.Hierarchy3Code,
  ItemAndBarcode_0.Hierarchy3Description,
  ItemAndBarcode_0.Hierarchy4Code,
  ItemAndBarcode_0.GroupCode,
  ItemAndBarcode_0.GroupDescription,
  ItemAndBarcode_0.ExternalStyle,
  ItemAndBarcode_0.VasGroupCode,
  ItemAndBarcode_0.ShortDescr,
  ItemAndBarcode_0.PutawayType,
  ItemAndBarcode_0.StackabilityCode,
  ItemAndBarcode_0.ProductLife,
  ItemAndBarcode_0.PercentAcceptableProductLife,
  ItemAndBarcode_0.LpnsPerTier,
  ItemAndBarcode_0.TiersPerPallet,
  ItemAndBarcode_0.VelocityCode,
  ItemAndBarcode_0.ReqBatchNbrFlg,
  ItemAndBarcode_0.HarmonizedTariffCode,
  ItemAndBarcode_0.HarmonizedTariffDescription,
  ItemAndBarcode_0.Description3,
  ItemAndBarcode_0.HostAwareItemFlg,
  ItemAndBarcode_0.UnNumber,
  ItemAndBarcode_0.UnClass,
  ItemAndBarcode_0.UnDescription,
  ItemAndBarcode_0.HazardStatement,
  ItemAndBarcode_0.ShippingTemperatureInstr
FROM wms_ItemAndBarcode AS ItemAndBarcode_0;

CREATE VIEW WMSService_Vendor AS SELECT
  Vendor_0.createdAt,
  Vendor_0.createdBy,
  Vendor_0.modifiedAt,
  Vendor_0.modifiedBy,
  Vendor_0.BusinessPartnerIdSAP,
  Vendor_0.VendorCode,
  Vendor_0.VendorName,
  Vendor_0.CustField1
FROM wms_Vendor AS Vendor_0;

CREATE VIEW WMSService_PurchaseOrder AS SELECT
  PurchaseOrder_0.createdAt,
  PurchaseOrder_0.createdBy,
  PurchaseOrder_0.modifiedAt,
  PurchaseOrder_0.modifiedBy,
  PurchaseOrder_0.PurchaseOrder,
  PurchaseOrder_0.BusinessPartnerIdSAP,
  PurchaseOrder_0.PoNbr,
  PurchaseOrder_0.FacilityCode,
  PurchaseOrder_0.VendorCode,
  PurchaseOrder_0.OrdDate,
  PurchaseOrder_0.RefNbr,
  PurchaseOrder_0.PoType,
  PurchaseOrder_0.DeliveryDate,
  PurchaseOrder_0.ShipDate,
  PurchaseOrder_0.CancelDate,
  PurchaseOrder_0.CustField1,
  PurchaseOrder_0.CustField3,
  PurchaseOrder_0.CustField4,
  PurchaseOrder_0.CustField5,
  PurchaseOrder_0.CustName,
  PurchaseOrder_0.CustAddr1
FROM wms_PurchaseOrder AS PurchaseOrder_0;

CREATE VIEW WMSService_PurchaseOrderItem AS SELECT
  PurchaseOrderItem_0.createdAt,
  PurchaseOrderItem_0.createdBy,
  PurchaseOrderItem_0.modifiedAt,
  PurchaseOrderItem_0.modifiedBy,
  PurchaseOrderItem_0.PurchaseOrderIdSap,
  PurchaseOrderItem_0.SeqNbr,
  PurchaseOrderItem_0.ProductIdSAP,
  PurchaseOrderItem_0.ItemPartA,
  PurchaseOrderItem_0.OrdQty,
  PurchaseOrderItem_0.CustField1,
  PurchaseOrderItem_0.CustField2,
  PurchaseOrderItem_0.to_PurchaseOrder_PurchaseOrder
FROM wms_PurchaseOrderItem AS PurchaseOrderItem_0;

CREATE VIEW WMSService_ASNHdrCompras AS SELECT
  ASNHdrCompras_0.createdAt,
  ASNHdrCompras_0.createdBy,
  ASNHdrCompras_0.modifiedAt,
  ASNHdrCompras_0.modifiedBy,
  ASNHdrCompras_0.PurchaseOrderIdSap,
  ASNHdrCompras_0.BusinessPartnerIdSAP,
  ASNHdrCompras_0.ShipmentNbr,
  ASNHdrCompras_0.FacilityCode,
  ASNHdrCompras_0.TrailerNbr,
  ASNHdrCompras_0.ShipmentType,
  ASNHdrCompras_0.VendorInfo,
  ASNHdrCompras_0.ShippedDate,
  ASNHdrCompras_0.CustField3
FROM wms_ASNHdrCompras AS ASNHdrCompras_0;

CREATE VIEW WMSService_ASNDtlCompras AS SELECT
  ASNDtlCompras_0.createdAt,
  ASNDtlCompras_0.createdBy,
  ASNDtlCompras_0.modifiedAt,
  ASNDtlCompras_0.modifiedBy,
  ASNDtlCompras_0.PurchaseOrderIdSap,
  ASNDtlCompras_0.SeqNbr,
  ASNDtlCompras_0.ProductIdSAP,
  ASNDtlCompras_0.ItemPartA,
  ASNDtlCompras_0.ShippedQty,
  ASNDtlCompras_0.PoNbr,
  ASNDtlCompras_0.PoSeqNbr,
  ASNDtlCompras_0.LpnLockCode,
  ASNDtlCompras_0.to_ASNCompras_PurchaseOrderIdSap
FROM wms_ASNDtlCompras AS ASNDtlCompras_0;

CREATE VIEW WMSService_OrderHdr AS SELECT
  OrderHdr_0.createdAt,
  OrderHdr_0.createdBy,
  OrderHdr_0.modifiedAt,
  OrderHdr_0.modifiedBy,
  OrderHdr_0.order_nbr,
  OrderHdr_0.facility_code,
  OrderHdr_0.company_code,
  OrderHdr_0.order_type,
  OrderHdr_0.ord_date,
  OrderHdr_0.req_ship_date,
  OrderHdr_0.cust_name,
  OrderHdr_0.cust_addr,
  OrderHdr_0.action_code,
  OrderHdr_0.route_nbr,
  OrderHdr_0.cust_city,
  OrderHdr_0.cust_state,
  OrderHdr_0.cust_country,
  OrderHdr_0.cust_nbr,
  OrderHdr_0.sales_channel,
  OrderHdr_0.cust_field_1,
  OrderHdr_0.cust_field_2,
  OrderHdr_0.cust_field_3,
  OrderHdr_0.cust_field_4,
  OrderHdr_0.cust_field_5,
  OrderHdr_0.cust_date_1,
  OrderHdr_0.cust_date_2,
  OrderHdr_0.cust_short_text_1,
  OrderHdr_0.cust_short_text_2,
  OrderHdr_0.cust_short_text_3,
  OrderHdr_0.cust_short_text_4,
  OrderHdr_0.cust_short_text_5,
  OrderHdr_0.cust_long_text_1,
  OrderHdr_0.cust_long_text_2
FROM wms_OrderHdr AS OrderHdr_0;

CREATE VIEW WMSService_OrderDtl AS SELECT
  OrderDtl_0.createdAt,
  OrderDtl_0.createdBy,
  OrderDtl_0.modifiedAt,
  OrderDtl_0.modifiedBy,
  OrderDtl_0.po_nbr,
  OrderDtl_0.seq_nbr,
  OrderDtl_0.item_part_a,
  OrderDtl_0.ord_qty,
  OrderDtl_0.action_code,
  OrderDtl_0.cost,
  OrderDtl_0.sale_price,
  OrderDtl_0.cust_field_2,
  OrderDtl_0.cust_field_5,
  OrderDtl_0.order_order_nbr
FROM wms_OrderDtl AS OrderDtl_0;

CREATE VIEW master_data_GlobalSettingMaster AS SELECT
  GlobalSetting_0.createdAt,
  GlobalSetting_0.createdBy,
  GlobalSetting_0.modifiedAt,
  GlobalSetting_0.modifiedBy,
  GlobalSetting_0.GlobalSettingId,
  GlobalSetting_0.GlobalSettingModule,
  GlobalSetting_0.GlobalSettingType,
  GlobalSetting_0.GlobalSettingName,
  GlobalSetting_0.GlobalSettingClassification,
  GlobalSetting_0.GlobalSettingCode,
  GlobalSetting_0.GlobalSettingValue,
  GlobalSetting_0.GlobalSettingValue2,
  GlobalSetting_0.GlobalSettingValue3,
  GlobalSetting_0.GlobalSettingValue4,
  GlobalSetting_0.GlobalSettingValue5,
  GlobalSetting_0.GlobalSettingDescription,
  GlobalSetting_0.GlobalSettingPatternId,
  GlobalSetting_0.GlobalSettingStatus,
  GlobalSetting_0.GlobalSettingIsEditable,
  GlobalSetting_0.GlobalSettingIsDeletable,
  GlobalSetting_0.GlobalSettingIsBlocked,
  GlobalSetting_0.terminal
FROM master_data_GlobalSetting AS GlobalSetting_0
WHERE GlobalSetting_0.GlobalSettingClassification = 'PATTERN';

CREATE VIEW master_data_GlobalSettingDetail AS SELECT
  GlobalSetting_0.createdAt,
  GlobalSetting_0.createdBy,
  GlobalSetting_0.modifiedAt,
  GlobalSetting_0.modifiedBy,
  GlobalSetting_0.GlobalSettingId,
  GlobalSetting_0.GlobalSettingModule,
  GlobalSetting_0.GlobalSettingType,
  GlobalSetting_0.GlobalSettingName,
  GlobalSetting_0.GlobalSettingClassification,
  GlobalSetting_0.GlobalSettingCode,
  GlobalSetting_0.GlobalSettingValue,
  GlobalSetting_0.GlobalSettingValue2,
  GlobalSetting_0.GlobalSettingValue3,
  GlobalSetting_0.GlobalSettingValue4,
  GlobalSetting_0.GlobalSettingValue5,
  GlobalSetting_0.GlobalSettingDescription,
  GlobalSetting_0.GlobalSettingPatternId,
  GlobalSetting_0.GlobalSettingStatus,
  GlobalSetting_0.GlobalSettingIsEditable,
  GlobalSetting_0.GlobalSettingIsDeletable,
  GlobalSetting_0.GlobalSettingIsBlocked,
  GlobalSetting_0.terminal
FROM master_data_GlobalSetting AS GlobalSetting_0
WHERE GlobalSetting_0.GlobalSettingClassification = 'CHILDREN';

CREATE VIEW JournalEntryService_ViewPreAsientoContable AS SELECT
  ViewPreAsientoContable_0.PreAsientoContableId,
  ViewPreAsientoContable_0.DocumentoCodigo,
  ViewPreAsientoContable_0.NumeroDocumentoOrigen,
  ViewPreAsientoContable_0.AccountingDocumentType,
  ViewPreAsientoContable_0.CompanyCode,
  ViewPreAsientoContable_0.DocumentDate,
  ViewPreAsientoContable_0.PostingDate,
  ViewPreAsientoContable_0.TransactionCurrency,
  ViewPreAsientoContable_0.CompanyCodeCurrency,
  ViewPreAsientoContable_0.GroupCurrency,
  ViewPreAsientoContable_0.FreeDefinedCurrency,
  ViewPreAsientoContable_0.CreatedByUser,
  ViewPreAsientoContable_0.OriginalReferenceDocument,
  ViewPreAsientoContable_0.OriginalReferenceDocumentLogicalSystem,
  ViewPreAsientoContable_0.AccountingDocument,
  ViewPreAsientoContable_0.DocumentReferenceID,
  ViewPreAsientoContable_0.DocumentHeaderText,
  ViewPreAsientoContable_0.ReversalReason,
  ViewPreAsientoContable_0.ReversalReferenceDocument,
  ViewPreAsientoContable_0.ReversalDate,
  ViewPreAsientoContable_0.TaxReportingDate,
  ViewPreAsientoContable_0.TaxDeterminationDate,
  ViewPreAsientoContable_0.TaxFulfillmentDate,
  ViewPreAsientoContable_0.DoTaxAmountCheck,
  ViewPreAsientoContable_0.InvoiceReceiptDate,
  ViewPreAsientoContable_0.ExchangeRateDate,
  ViewPreAsientoContable_0.IndirectQuotedExchangeRate,
  ViewPreAsientoContable_0.ExchangeRate,
  ViewPreAsientoContable_0.SourceSystemCompanyCode,
  ViewPreAsientoContable_0.SourceSystemAccountingDocument,
  ViewPreAsientoContable_0.Reference1InDocumentHeader,
  ViewPreAsientoContable_0.Reference2InDocumentHeader,
  ViewPreAsientoContable_0.JrnlEntryCntrySpecificRef1,
  ViewPreAsientoContable_0.JrnlEntryCntrySpecificDate1,
  ViewPreAsientoContable_0.JrnlEntryCntrySpecificRef2,
  ViewPreAsientoContable_0.JrnlEntryCntrySpecificDate2,
  ViewPreAsientoContable_0.JrnlEntryCntrySpecificRef3,
  ViewPreAsientoContable_0.JrnlEntryCntrySpecificDate3,
  ViewPreAsientoContable_0.JrnlEntryCntrySpecificRef4,
  ViewPreAsientoContable_0.JrnlEntryCntrySpecificDate4,
  ViewPreAsientoContable_0.JrnlEntryCntrySpecificRef5,
  ViewPreAsientoContable_0.JrnlEntryCntrySpecificDate5,
  ViewPreAsientoContable_0.JrnlEntryCntrySpecificBp1,
  ViewPreAsientoContable_0.JrnlEntryCntrySpecificBp2,
  ViewPreAsientoContable_0.NroDocumentoSap,
  ViewPreAsientoContable_0.FechaHoraCreacion,
  ViewPreAsientoContable_0.StatusName,
  ViewPreAsientoContable_0.StatusId,
  ViewPreAsientoContable_0.Flujo
FROM JournalEntry_ViewPreAsientoContable AS ViewPreAsientoContable_0;

CREATE VIEW LetrasService_Company AS SELECT
  Company_0.companyCode,
  Company_0.companyCodeName,
  Company_0.cityName,
  Company_0.country,
  Company_0.currency,
  Company_0."LANGUAGE",
  Company_0.company,
  Company_0.creditControlArea,
  Company_0.extendedWhldgTaxIsActive,
  Company_0.companyLogo,
  Company_0.companyIdentification,
  Company_0.companyPrincipalAddress
FROM Letras_Company AS Company_0;

CREATE VIEW LetrasService_Currency AS SELECT
  Currency_0.CurrencyCode,
  Currency_0.CurrencyName,
  Currency_0.CurrencySymbol
FROM Letras_Currency AS Currency_0;

CREATE VIEW LetrasService_ViewPlanilla AS SELECT
  ViewPlanilla_0.ID,
  ViewPlanilla_0.createdAt,
  ViewPlanilla_0.createdBy,
  ViewPlanilla_0.modifiedAt,
  ViewPlanilla_0.modifiedBy,
  ViewPlanilla_0.NroLetras,
  ViewPlanilla_0.Planilla,
  ViewPlanilla_0.ImporteTotal,
  ViewPlanilla_0.Moneda,
  ViewPlanilla_0.BancoCodigo,
  ViewPlanilla_0.BancoNombre,
  ViewPlanilla_0.CompanyCode,
  ViewPlanilla_0.CompanyName,
  ViewPlanilla_0.EstadoPlanillaCode,
  ViewPlanilla_0.EstadoPlanillaName
FROM Letras_ViewPlanilla AS ViewPlanilla_0;

CREATE VIEW LetrasService_LetrasCube AS SELECT
  LetrasCube_0.ID,
  LetrasCube_0.createdAt,
  LetrasCube_0.createdBy,
  LetrasCube_0.modifiedAt,
  LetrasCube_0.modifiedBy,
  LetrasCube_0.Code,
  LetrasCube_0.Sequence,
  LetrasCube_0.Documento,
  LetrasCube_0.Serie,
  LetrasCube_0.Numero,
  LetrasCube_0.CodigoMoneda,
  LetrasCube_0.FechaEmision,
  LetrasCube_0.Dias,
  LetrasCube_0.FechaVencimiento,
  LetrasCube_0.TipoCambio,
  LetrasCube_0.Referencia,
  LetrasCube_0.TotalMonedaDocumento,
  LetrasCube_0.TotalDolares,
  LetrasCube_0.Vendedor,
  LetrasCube_0.CodigoJournalEntry,
  LetrasCube_0.JournalEntryItem,
  LetrasCube_0.FiscalYear,
  LetrasCube_0.EstadoLetras_Codigo,
  LetrasCube_0.Planilla_ID,
  LetrasCube_0.TipoLetra_Codigo,
  LetrasCube_0.TipoLetraComposition,
  LetrasCube_0.EstadoLetraComposition
FROM Letras_LetrasCube AS LetrasCube_0;

CREATE VIEW MasterDataService_ViewGlobalSettingPatterns AS SELECT
  ViewGlobalSettingPatterns_0.createdAt,
  ViewGlobalSettingPatterns_0.createdBy,
  ViewGlobalSettingPatterns_0.modifiedAt,
  ViewGlobalSettingPatterns_0.modifiedBy,
  ViewGlobalSettingPatterns_0.GlobalSettingId,
  ViewGlobalSettingPatterns_0.GlobalSettingModule,
  ViewGlobalSettingPatterns_0.GlobalSettingType,
  ViewGlobalSettingPatterns_0.GlobalSettingName,
  ViewGlobalSettingPatterns_0.GlobalSettingClassification,
  ViewGlobalSettingPatterns_0.GlobalSettingCode,
  ViewGlobalSettingPatterns_0.GlobalSettingValue,
  ViewGlobalSettingPatterns_0.GlobalSettingValue2,
  ViewGlobalSettingPatterns_0.GlobalSettingValue3,
  ViewGlobalSettingPatterns_0.GlobalSettingValue4,
  ViewGlobalSettingPatterns_0.GlobalSettingValue5,
  ViewGlobalSettingPatterns_0.GlobalSettingDescription,
  ViewGlobalSettingPatterns_0.GlobalSettingPatternId,
  ViewGlobalSettingPatterns_0.GlobalSettingStatus,
  ViewGlobalSettingPatterns_0.GlobalSettingIsEditable,
  ViewGlobalSettingPatterns_0.GlobalSettingIsDeletable,
  ViewGlobalSettingPatterns_0.GlobalSettingIsBlocked,
  ViewGlobalSettingPatterns_0.terminal
FROM master_data_ViewGlobalSettingPatterns AS ViewGlobalSettingPatterns_0;

CREATE VIEW MasterDataService_Type AS SELECT
  Types_0.GlobalSettingType
FROM master_data_Types AS Types_0;

CREATE VIEW MasterDataService_Module AS SELECT
  Modules_0.GlobalSettingModule
FROM master_data_Modules AS Modules_0;

CREATE VIEW TrazabilidadService_EventView AS SELECT
  EventView_0.ID,
  EventView_0.EventInitDateTime,
  EventView_0.EventFinishDateTime,
  EventView_0.to_EventType_Code,
  EventView_0.to_Status_Code
FROM trazabilidad_EventView AS EventView_0;

